# =============================================================================
# PSX Decompilation Project Makefile
# =============================================================================
# This Makefile provides the build infrastructure for a PSX decompilation
# project using splat and the GCC 2.6/2.7 era PSX toolchain.
#
# Based on conventions from sotn-decomp, open-ribbon, and other PSX decomps.
# =============================================================================

# -----------------------------------------------------------------------------
# Configuration - Adjust these for your project
# -----------------------------------------------------------------------------

# Project name (used for output files)
PROJECT := game

# Game version (us, eu, jp, etc.)
# SLES_010.90
VERSION := pal

# Target binary (the original PSX executable to match)
TARGET := disks/$(VERSION)/SLES_010.90

# Splat configuration file
SPLAT_CONFIG := config/splat.$(VERSION).yaml

# Build output directory
BUILD_DIR := build/$(VERSION)

# ASM output directory (from splat)
ASM_DIR := asm/$(VERSION)

# Source directory
SRC_DIR := src

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# Toolchain Configuration
# -----------------------------------------------------------------------------
# GCC Version: 2.7.2-psx matches existing decompiled functions.
# Note: 2.5.7-psx produces better matches for some functions (e.g., func_8007A62C)
# but breaks existing matches. May need per-file compiler selection in future.
# Available versions: 2.5.7-psx, 2.6.0-psx, 2.6.3-psx, 2.7.2-psx, 2.8.0-psx,
#                     2.8.1-psx, 2.91.66-psx, 2.95.2-psx
# Download with: ./scripts/build_old_gcc.sh <version>
GCC_VERSION := 2.7.2-psx
GCC_DIR := tools/gcc-builds/gcc-$(GCC_VERSION)
CC1 := $(GCC_DIR)/cc1
GCC := $(GCC_DIR)/gcc

# MIPS cross-toolchain (from Nix environment)
# Note: Nix provides mipsel-unknown-linux-gnu-*, not mipsel-linux-gnu-*
# The binutils (as, ld, objcopy) are version-independent for linking
CROSS := mipsel-unknown-linux-gnu-
AS := $(CROSS)as
LD := $(CROSS)ld
OBJCOPY := $(CROSS)objcopy
CPP := cpp
STRIP := $(CROSS)strip

# maspsx - Modern ASPSX replacement
# Transforms GCC assembly output to match PSY-Q ASPSX.EXE behavior
# See: https://github.com/mkst/maspsx
MASPSX := python3 tools/maspsx/maspsx.py

# maspsx configuration (adjust based on your game's PSY-Q version)
# PSY-Q 3.3 -> --aspsx-version=2.21
# PSY-Q 3.5 -> --aspsx-version=2.34
# PSY-Q 4.0 -> --aspsx-version=2.56
# PSY-Q 4.1 -> --aspsx-version=2.67
# PSY-Q 4.3 -> --aspsx-version=2.77
# PSY-Q 4.4 -> --aspsx-version=2.79
# PSY-Q 4.5 -> --aspsx-version=2.81
# PSY-Q 4.6 -> --aspsx-version=2.86
# PSY-Q 4.7 -> --aspsx-version=2.86 (same as 4.6)
ASPSX_VERSION := 2.86
MASPSX_FLAGS := --aspsx-version=$(ASPSX_VERSION) --run-assembler --gnu-as-path=$(AS)

# Python (from Nix environment)
PYTHON := python3

# splat binary splitting tool
SPLAT := $(PYTHON) -m splat split

# m2c - MIPS to C decompiler
M2C := $(PYTHON) tools/m2c/m2c.py
SPLAT := $(PYTHON) -m splat split

# m2c - MIPS to C decompiler
M2C := $(PYTHON) tools/m2c/m2c.py

# -----------------------------------------------------------------------------
# Compiler Flags
# -----------------------------------------------------------------------------

# C preprocessor flags
CPPFLAGS := -I include -I psyq -D_LANGUAGE_C -DVERSION_$(VERSION)

# PSX compiler flags (GCC 2.6 compatible)
# -O2: Optimization level 2
# -G8: Small data threshold (variables <=8 bytes go in .sdata for GP-relative access)
# -fno-builtin: Don't use builtin functions
# -mno-abicalls: No PIC/position independent code
# -mcpu=3000: MIPS R3000 (PSX CPU)
CFLAGS := -O2 -G8 -fno-builtin -mno-abicalls -mcpu=3000

# Assembler flags
ASFLAGS := -march=r3000 -mtune=r3000 -no-pad-sections -G8 -Iinclude

# Linker flags
LDFLAGS := -nostdlib

# -----------------------------------------------------------------------------
# File Discovery
# -----------------------------------------------------------------------------

# Find all C source files
C_SRCS := $(shell find $(SRC_DIR) -name '*.c' 2>/dev/null)

# Find all ASM source files (from splat extraction)
# Exclude nonmatchings/ - those are included by C files via INCLUDE_ASM
S_SRCS := $(shell find $(ASM_DIR) -name '*.s' -not -path '*/nonmatchings/*' 2>/dev/null)

# Find all binary assets (from splat extraction)
BIN_SRCS := $(shell find assets -name '*.bin' 2>/dev/null)

# Object files - paths must match what splat generates in the linker script
# splat outputs: build/pal/asm/pal/file.o (build_path + source path with .s -> .o)
C_OBJS := $(C_SRCS:%.c=$(BUILD_DIR)/%.o)
S_OBJS := $(S_SRCS:%.s=$(BUILD_DIR)/%.o)
BIN_OBJS := $(BIN_SRCS:%.bin=$(BUILD_DIR)/%.o)

# All object files
OBJS := $(C_OBJS) $(S_OBJS) $(BIN_OBJS)

# Linker script (generated by splat)
LD_SCRIPT := $(BUILD_DIR)/$(PROJECT).ld

# -----------------------------------------------------------------------------
# Targets
# -----------------------------------------------------------------------------

.PHONY: all clean extract expected diff context check tools help

# Default target - uses recursive make if ASM files don't exist
all:
	@if [ ! -d "$(ASM_DIR)" ]; then \
		echo "ASM directory missing, running splat..."; \
		$(SPLAT) $(SPLAT_CONFIG); \
	fi
	@$(MAKE) --no-print-directory build
	@echo "Build complete!"

# Actual build target (called after ASM exists)
.PHONY: build
build: $(BUILD_DIR)/$(PROJECT).bin

# Show help
help:
	@echo "PSX Decompilation Project (Modern Workflow)"
	@echo "============================================"
	@echo ""
	@echo "Toolchain: GCC $(GCC_VERSION) + maspsx (ASPSX $(ASPSX_VERSION))"
	@echo ""
	@echo "Targets:"
	@echo "  all              - Build the project (default, byte-matching)"
	@echo "  extract          - Extract/disassemble binary using splat"
	@echo "  expected         - Copy original binary to expected/"
	@echo "  check            - Verify build matches original (quick)"
	@echo "  verify           - Alias for 'check' (for compatibility)"
	@echo "  clean            - Remove build artifacts"
	@echo ""
	@echo "Decompilation:"
	@echo "  diff FUNC=name   - Compare function with asm-differ"
	@echo "  decompile FUNC=f - Decompile function with m2c"
	@echo "  context          - Generate ctx.c for m2c"
	@echo "  permuter FUNC=f  - Run decomp-permuter"
	@echo ""
	@echo "Tools:"
	@echo "  tools            - Download GCC toolchain"
	@echo "  detect-compiler  - Analyze binary's compiler"
	@echo ""
	@echo "Workflow:"
	@echo "  1. ./tools/download-toolchain.sh"
	@echo "  2. Place binary in disks/$(VERSION)/"
	@echo "  3. make extract"
	@echo "  4. make"
	@echo "  5. make check"
	@echo ""

# -----------------------------------------------------------------------------
# Extraction (splat)
# -----------------------------------------------------------------------------

extract: $(SPLAT_CONFIG)
	@echo "Extracting binary using splat..."
	$(SPLAT) $(SPLAT_CONFIG)
	@echo "Extraction complete. ASM files in $(ASM_DIR)/"

# Generate linker script and ASM files if they don't exist
$(LD_SCRIPT): $(SPLAT_CONFIG) $(BASEROM)
	@echo "Running splat to generate linker script and ASM..."
	$(SPLAT) $(SPLAT_CONFIG)

# -----------------------------------------------------------------------------
# Compilation Rules
# -----------------------------------------------------------------------------

# Create build directories
$(BUILD_DIR)/:
	mkdir -p $@

# Compile C to object file using old-gcc + maspsx pipeline
# This is the MODERN approach that doesn't require wine/dosemu2:
#   1. Preprocess with system cpp
#   2. Compile with old gcc cc1 (same codegen as PSY-Q)
#   3. Pass through maspsx (replicates ASPSX.EXE behavior)
#   4. Assemble with GNU as (via maspsx --run-assembler)
#
# The maspsx wrapper handles:
#   - $gp-relative addressing
#   - NOP insertion for pipeline hazards
#   - div/rem expansion
#   - .comm/.sdata handling
$(BUILD_DIR)/%.o: %.c | $(BUILD_DIR)/
	@mkdir -p $(dir $@)
	@echo "CC $<"
	$(CPP) $(CPPFLAGS) $< | $(CC1) $(CFLAGS) -o $(BUILD_DIR)/$*.s
	$(MASPSX) $(MASPSX_FLAGS) -o $@ $(ASFLAGS) $(BUILD_DIR)/$*.s

# Assemble ASM files (from splat extraction or handwritten)
# Output to build/pal/asm/pal/*.o to match splat linker script
$(BUILD_DIR)/%.o: %.s | $(BUILD_DIR)/
	@mkdir -p $(dir $@)
	@echo "AS $<"
	@$(AS) $(ASFLAGS) $< -o $@

# Convert binary assets to object files
# Uses objcopy to wrap raw binary data into an ELF object
$(BUILD_DIR)/%.o: %.bin | $(BUILD_DIR)/
	@mkdir -p $(dir $@)
	@echo "BIN $<"
	@$(OBJCOPY) -I binary -O elf32-tradlittlemips -B mips $< $@

# -----------------------------------------------------------------------------
# Linking
# -----------------------------------------------------------------------------

# Undefined symbols (generated by splat)
UNDEFINED_SYMS := undefined_syms_auto.txt
UNDEFINED_FUNCS := undefined_funcs_auto.txt

# Link all objects into ELF
$(BUILD_DIR)/$(PROJECT).elf: $(OBJS) $(LD_SCRIPT) $(UNDEFINED_SYMS) $(UNDEFINED_FUNCS)
	@echo "LD $@"
	@$(LD) $(LDFLAGS) -T $(LD_SCRIPT) -T $(UNDEFINED_SYMS) -T $(UNDEFINED_FUNCS) -Map $(BUILD_DIR)/$(PROJECT).map -o $@ $(OBJS)

# Convert ELF to raw binary (PSX format)
$(BUILD_DIR)/$(PROJECT).bin: $(BUILD_DIR)/$(PROJECT).elf
	@echo "OBJCOPY $@"
	@$(OBJCOPY) -O binary $< $@

# -----------------------------------------------------------------------------
# Verification
# -----------------------------------------------------------------------------

# Create expected directory with original binary for comparison
expected: $(TARGET)
	@mkdir -p expected/$(VERSION)
	@cp $(TARGET) expected/$(VERSION)/
	@echo "Copied original to expected/$(VERSION)/"

# Check if build matches original
check: $(BUILD_DIR)/$(PROJECT).bin $(TARGET)
	@echo "Comparing build to original..."
	@sha1sum $(BUILD_DIR)/$(PROJECT).bin $(TARGET)
	@if cmp -s $(BUILD_DIR)/$(PROJECT).bin $(TARGET); then \
		echo "✓ BUILD MATCHES ORIGINAL"; \
	else \
		echo "✗ BUILD DOES NOT MATCH"; \
		exit 1; \
	fi

# Verify: Compatibility alias for 'check'
# Usage: make verify
verify: check

# -----------------------------------------------------------------------------
# Diff Tools
# -----------------------------------------------------------------------------

# Side-by-side binary diff
# Usage: make bindiff
bindiff: $(BUILD_DIR)/$(PROJECT).bin
	$(PYTHON) scripts/bindiff.py $(BUILD_DIR)/$(PROJECT).bin $(TARGET)

# Run asm-differ on a function
# Usage: make diff FUNC=FunctionName
diff:
ifndef FUNC
	@echo "Usage: make diff FUNC=FunctionName"
	@exit 1
endif
	$(PYTHON) tools/asm-differ/diff.py -mw3 $(FUNC)

# Decompile a function using m2c
# Usage: make decompile FUNC=FunctionName
# The function must exist in asm/pal/nonmatchings/*/FUNC.s
decompile:
ifndef FUNC
	@echo "Usage: make decompile FUNC=FunctionName"
	@exit 1
endif
	@ASM_FILE=$$(find $(ASM_DIR)/nonmatchings -name "$(FUNC).s" 2>/dev/null | head -1); \
	if [ -z "$$ASM_FILE" ]; then \
		echo "Error: Could not find $(FUNC).s in $(ASM_DIR)/nonmatchings/"; \
		exit 1; \
	fi; \
	$(PYTHON) tools/m2c/m2c.py -t mipsel-gcc-c "$$ASM_FILE"

# Import function into decomp-permuter
# Usage: make permuter-import FILE=src/main.c FUNC=FunctionName
permuter-import:
ifndef FILE
	@echo "Usage: make permuter-import FILE=src/main.c FUNC=FunctionName"
	@exit 1
endif
	$(PYTHON) tools/decomp-permuter/import.py $(FILE)

# Run decomp-permuter on imported function
# Usage: make permuter FUNC=FunctionName
permuter:
ifndef FUNC
	@echo "Usage: make permuter FUNC=FunctionName"
	@exit 1
endif
	$(PYTHON) tools/decomp-permuter/permuter.py nonmatchings/$(FUNC) --best-only -j4

# -----------------------------------------------------------------------------
# Cleanup
# -----------------------------------------------------------------------------

clean:
	rm -rf $(BUILD_DIR)
	rm -rf asm
	rm -rf assets

# Clean only build artifacts, keep extracted files
clean-build:
	rm -rf $(BUILD_DIR)

# =============================================================================
# Launch PCSX-Redux in debug mode (requires nixGL for OpenGL on non-NixOS)
# Connect Ghidra debugger to localhost:3333
# TODO: Use the flake's nixGLIntel wrapper instead of 'nix run' once we figure out
#       how to make the overlay work with --impure for host GPU driver access
# Override with: make emu ISO=path/to/game.iso
ISO ?= disks/$(VERSION)/sles-01090.iso01.iso
ELF := $(BUILD_DIR)/$(PROJECT).elf
GDB_PORT := 3333

# PCSX-Redux executable (via nixGL for GPU access)
# Note: \# escapes the hash which Make treats as comment
PCSX := nix run --impure github:nix-community/nixGL\#nixGLIntel -- pcsx-redux

# Launch PCSX-Redux emulator with GDB server (runs in foreground)
# NOTE: Web server must be enabled manually in GUI:
#   Configuration > Emulation > Enable Web Server
emu:
	$(PCSX) -interpreter -debugger -gdb -iso $(ISO) -run -fastboot

# Run MCP server for Copilot integration
# PCSX-Redux must have web server enabled on port 8080
# Enable: Configuration > Emulation > Enable Web Server
mcp-server:
	python3 scripts/pcsx_mcp_server.py

# Run a Lua script in PCSX-Redux
# Usage: make lua SCRIPT=scripts/hello.lua
# Note: -interpreter -debugger required for breakpoints to work
lua:
ifndef SCRIPT
	@echo "Usage: make lua SCRIPT=scripts/hello.lua"
	@exit 1
endif
	$(PCSX) -interpreter -debugger -lua_stdout -iso $(ISO) -dofile $(SCRIPT) -run

# Run inline Lua code
# Usage: make lua-exec CODE='print("hello")'
lua-exec:
ifndef CODE
	@echo "Usage: make lua-exec CODE='print(\"hello\")'"
	@exit 1
endif
	$(PCSX) -lua_stdout -iso $(ISO) -exec '$(CODE)' -run

# Print debug instructions for Ghidra native debugger
debug:
	@echo "=== PSX Debug Session (Ghidra Native Debugger) ==="
	@echo ""
	@echo "1. Run 'make emu' to start PCSX-Redux with GDB server on port $(GDB_PORT)"
	@echo ""
	@echo "2. In Ghidra:"
	@echo "   a. Right-click project -> 'Open With' -> 'Debugger'"
	@echo "   b. In 'Debugger Targets' window, click the connector button (top-right)"
	@echo "   c. Select 'gdb' from dropdown"
	@echo "   d. Set launch command to:"
	@echo "      ghidra-gdb -i mi2"
	@echo "   e. Click 'Connect'"
	@echo ""
	@echo "3. In Ghidra's GDB Interpreter window:"
	@echo "   (gdb) source $(CURDIR)/tools/ghidra_debugger_scripts"
	@echo "   (gdb) target remote localhost:$(GDB_PORT)"
	@echo ""
	@echo "4. In 'Modules' tab: right-click top line -> 'Map Module to <your project>'"
	@echo ""
	@echo "You're now debugging! Use Ghidra's debugger controls (F5=continue, F10=step, etc.)"

