"""Brute search for the tutorial-sign sprite name (multi-instruction wood sign)."""
import sys
sys.path.insert(0, 'tools/scripts')
from calchash import calcHash

TARGET = 0x80729081

# The sprite shows ~10 frames with different power-up instructions (CLAY BALL, SWIRLY Q,
# UNIVERSE ENEMA, SUPER WILLIE, SLAPPY HAMSTER, etc.). It is a 'hint/tutorial sign board'.
candidates = [
    # sign / hint / info / tutorial
    'HINT','HINTS','HINT_SIGN','HINTSIGN','HINT_BOARD','HINTBOARD','HINT_BD','HINTBD',
    'SIGN','SIGNS','SIGNBOARD','SIGN_BOARD','SIGN_PANEL','SIGNPANEL','SIGN_BD','BIG_SIGN','BIGSIGN',
    'INFO','INFOS','INFO_SIGN','INFOSIGN','INFO_BOARD','INFOBOARD','INFO_PANEL','INFOPANEL',
    'INFO_BD','INFO_ROCK','INFOROCK','INFO_STONE','INFO_PLAQUE','INFOPLAQUE','PLAQUE',
    'INSTRUCT','INSTRUCTION','INSTRUCTIONS','INSTRUCT_SIGN','INSTR','INSTR_SIGN','INSTRSIGN',
    'INSTRUCTION_SIGN','INSTRUCTION_BOARD','INSTRUCTIONBOARD','INSTR_BOARD','INSTRBOARD',
    'TUTORIAL','TUTORIAL_SIGN','TUTORIALSIGN','TUTORIAL_BOARD','TUTORIALBOARD','TUTORIALBD',
    'TUT','TUT_SIGN','TUTSIGN','TIPSIGN','TIP_SIGN','TIPS','TIP','TIP_BOARD',
    'HOWTO','HOWTOSIGN','HOWTO_SIGN','HELP_SIGN','HELPSIGN','HELP','HELPER',
    'HELP_BOARD','HELPBOARD','HELP_PANEL','HELPPANEL','HELP_BD',
    'MSG','MESSAGE','MESSAGE_SIGN','MSGSIGN','MSG_BOARD','MSGBOARD','MESSAGE_BOARD',
    'BANNER','BANNERSIGN','BANNER_SIGN','BANNERBOARD','BANNER_BOARD',
    'NOTE','NOTES','NOTE_BOARD','NOTEBOARD','NOTE_SIGN','NOTESIGN','NOTE_PANEL',
    'SCROLL','SCROLLS','SCROLL_SIGN','SCROLL_BOARD',
    # Totem (from the function comment)
    'TOTEM','TOTEMSIGN','TOTEM_SIGN','TOTEM_BOARD','TOTEMBOARD',
    'TOTEM_HINT','TOTEMHINT','TOTEM_INFO','TOTEMINFO','TOTEM_TIP','TOTEMTIP',
    'TOTEM_INSTR','TOTEM_TUT','TOTEM_HELP','TOTEM_MSG','TOTEM_NOTE',
    'BIGTOTEM','BIG_TOTEM','SIGN_TOTEM','SIGNTOTEM',
    # Tablet/Plaque/Marker
    'TABLET','TABLETS','TABLET_SIGN','TABLET_HINT',
    'MARKER','MARKERS','MARKER_SIGN','MARKER_BOARD',
    'PILLAR','PILLAR_SIGN','PILLAR_BOARD',
    # Wooden/Stone
    'WOODSIGN','WOOD_SIGN','WOODEN_SIGN','WOODENSIGN','SIGN_WOOD','SIGNWOOD',
    'STONESIGN','STONE_SIGN','STONE_BOARD','STONEBOARD','WALLSIGN','WALL_SIGN',
    # Klay-related
    'KLAY_SIGN','KLAYSIGN','KLAYINFO','KLAY_INFO','KLAY_HINT','KLAYHINT',
    'KLAYBANNER','KLAY_BANNER','KLAYTIP','KLAY_TIP','KLAY_HELP','KLAYHELP',
    'KLAYMEN_SIGN','KLAYMENSIGN','KLAYMEN_INFO','KLAYMEN_HINT',
    # Pickup-specific
    'PICKUP_SIGN','PICKUPSIGN','PICKUP_BOARD','PICKUPBOARD','PICKUP_INFO','PICKUPINFO',
    'PICKUP_HINT','PICKUPHINT','PICKUP_TUT','PICKUP_TIP','PICKUPTIP','POWERUP_SIGN','POWERUPSIGN',
    'POWERUP_INFO','POWERUPINFO','POWERUP_HINT','POWERUPHINT',
    # Generic UI/HUD
    'HUD_SIGN','HUD_HINT','HUD_INFO','HUD_TIP','UI_SIGN','UI_HINT','UI_INFO','UI_TIP',
    # Checkpoint relevant
    'CHECKPOINT','CHECKPOINT_SIGN','CHECKPOINT_BOARD','CHECKPOINT_PANEL',
    'CHKPT','CHKPT_SIGN','CHKPT_BOARD','CKPT_SIGN','CHECK_SIGN','CHECKSIGN',
    'CHECK','CHECK_BOARD','CHECKBOARD',
    # 'Item' or 'Object'
    'ITEM_SIGN','ITEMSIGN','ITEM_INFO','ITEMINFO','ITEM_HINT','ITEMHINT',
    'OBJECT_SIGN','OBJ_SIGN','OBJSIGN','OBJ_HINT','OBJ_INFO',
    # 'Power' / 'Special'
    'POWER_SIGN','POWERSIGN','POWER_HINT','POWERHINT','SPECIAL_SIGN','SPECIALSIGN',
    'POWER_TIP','POWER_INFO',
    # ToolX-style: SPRT/SEQ + suffix
    'SPRT_HINT','SPRT_SIGN','SPRT_INFO','SEQ_HINT','SEQ_SIGN','S_SIGN','S_HINT','S_INFO',
    # 'Spell' (since it teaches you about power-ups)
    'SPELL_SIGN','SPELLSIGN','SPELL_BOARD','SPELL_HINT',
    # Tutorial themes
    'GUIDE','GUIDE_SIGN','GUIDESIGN','GUIDE_BOARD','GUIDEBOARD','TUTORIAL_GUIDE',
    'LEARN','LEARN_SIGN','LEARNSIGN','LEARN_BOARD','LEARNBOARD',
    'READ','READ_SIGN','READSIGN','READ_BOARD',
    # Pause
    'PAUSE_INFO','PAUSEINFO','PAUSE_HINT','PAUSEHINT','PAUSE_HELP',
    # Decor
    'DECOR_SIGN','DECORSIGN','DECOR_HINT','DECORHINT','DECOR_INFO',
    'POWERUP_DECOR','POWERUPDECOR','HELP_DECOR','TUT_DECOR','TUT_DECORATION',
    # Generic
    'SIGN_POST','SIGNPOST','HINT_POST','HINTPOST',
    # Combination with level prefix
    'PHRO_SIGN','SCIE_SIGN','TMPL_SIGN','MENU_SIGN','BOIL_SIGN','SNOW_SIGN','FINN_SIGN',
    'WEED_SIGN',
    # Sprite prefix
    'SPR_SIGN','SPR_HINT','SPR_INFO','SPR_INSTR','SPR_TUT','SPR_HELP','SPR_TIP',
    'SPRITE_SIGN','SPRITE_HINT','SPRITE_INFO','SPRITE_INSTR','SPRITE_TUT','SPRITE_HELP',
]

print('Testing %d candidates against TARGET=0x%08x' % (len(candidates), TARGET))
for n in candidates:
    h = calcHash(n)
    if h == TARGET:
        print('  HIT: %s -> 0x%08x' % (n, h))
print('done')
