"""Validate 0x34014841 - JoeHeadJoe ball impact sound (also used in KLOG;RUNN levels)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from calchash import calcHash

T = 0x34014841
print(f"Target 0x34014841 (JoeHeadJoe ball impact / splat, KLOG;RUNN):\n")

cands = [
    "FX_BEEP_BRONZE_08","FX_BALL_LAND","FX_BALL_LAND_01","FX_BALL_LAND_02",
    "FX_BALL_SPLAT","FX_BALL_THUD","FX_BALL_HIT","FX_BALL_DROP",
    "FX_BALL_BOUNCE","FX_BALL_FALL","FX_BALL_BURST","FX_BALL_BREAK",
    "FX_HEAD_BALL_LAND","FX_HEAD_BALL_SPLAT","FX_HEAD_BALL_BOUNCE",
    "FX_JOE_BALL_LAND","FX_JOE_BALL_SPLAT","FX_JOE_BALL_BOUNCE",
    "FX_CLAY_LAND","FX_CLAY_SPLAT","FX_CLAY_THUD","FX_CLAY_BOUNCE",
    "FX_CLAYBALL_LAND","FX_CLAYBALL_SPLAT","FX_CLAYBALL_BOUNCE",
    "FX_BLB_LAND","FX_BLB_SPLAT","FX_BLB_BOUNCE","FX_BLB_HIT","FX_BLB_THUD",
    "FX_SKULL_BALL_LAND","FX_SKULL_BALL_SPLAT",
    "FX_BIG_THUD","FX_BIG_LAND","FX_BIG_SPLAT","FX_BIG_BOUNCE",
    "FX_HEAVY_THUD","FX_HEAVY_LAND","FX_HEAVY_SPLAT","FX_HEAVY_HIT",
    "FX_THUD","FX_THUD_01","FX_THUD_02","FX_BIG_HIT_01","FX_HIT_HEAVY",
    "FX_KLOG_BALL_LAND","FX_KLOG_SPLAT","FX_KLOG_THUD",
    "FX_RUNN_LAND","FX_RUNN_SPLAT","FX_RUNN_THUD","FX_RUNN_BALL_LAND",
    "FX_SPLAT_BIG","FX_SPLAT_HEAVY","FX_SPLAT_01","FX_SPLAT_02",
    "FX_GIB_LAND","FX_GIB_SPLAT","FX_GIBLET_LAND","FX_GIBLET_SPLAT",
    "FX_CHUNK_LAND","FX_CHUNK_SPLAT","FX_CHUNK_THUD","FX_CHUNK_HIT",
    "FX_BOMB_LAND","FX_BOMB_DROP","FX_BOMB_THUD","FX_BOMB_HIT",
    "FX_MINE_LAND","FX_MINE_DROP","FX_MINE_THUD","FX_MINE_HIT",
    "FX_ROCK_LAND","FX_ROCK_DROP","FX_ROCK_THUD","FX_ROCK_HIT",
    "FX_BRICK_LAND","FX_BRICK_DROP","FX_BRICK_THUD","FX_BRICK_HIT",
    "FX_STONE_LAND","FX_STONE_DROP","FX_STONE_THUD","FX_STONE_HIT",
    "FX_LAND_BIG","FX_LAND_HEAVY","FX_LAND_HARD","FX_LAND_THUD",
    "FX_DROP_BIG","FX_DROP_HEAVY","FX_DROP_HARD","FX_DROP_THUD",
    "FX_HIT_BIG","FX_HIT_HEAVY","FX_HIT_HARD","FX_HIT_THUD",
    "FX_BOSS_LAND","FX_BOSS_DROP","FX_BOSS_THUD","FX_BOSS_HIT","FX_BOSS_SPLAT",
    "FX_BOSS_BALL_LAND","FX_BOSS_BALL_SPLAT","FX_BOSS_BALL_BOUNCE",
    "FX_CLOSE","FX_SHUT","FX_SMACK","FX_PLOP","FX_PLOP_01","FX_PLOP_02",
    "FX_KICK","FX_PUNCH","FX_SLAP","FX_HIT","FX_HIT_LAND",
    "SFX_BALL_LAND","SFX_BALL_SPLAT","SFX_BALL_THUD",
]
for n in cands:
    h = calcHash(n)
    if h == T:
        print(f"  {n:30s} -> 0x{h:08x} <-- TARGET")
