"""TriggerCollectible100CTickCallback uses 0x62000441. What is it?
The 100C name suggests '100 collectible' (1970 bonus stage entry?).
Also try the InitSingleFrameDecorEntity (0x08624580 sprite).
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from calchash import calcHash

T = 0x62000441
T2 = 0x4a806042  # ClaySingle pickup
T3 = 0x42906465  # Hamster (regular)
T4 = 0xc2906565  # Hamster (3rd/full)

# 100C is the most common centennial-bonus theme - 100 collected
NAMES_100C = [
    "FX_PICKUP_100","FX_PICKUP_100C","FX_PICKUP_100_C","FX_PICKUP_C100",
    "FX_PICKUP_100_COIN","FX_PICKUP_100COIN","FX_PICKUP_HUNDRED","FX_PICKUP_HUNDREDC",
    "FX_100C","FX_100","FX_100_C","FX_HUNDRED","FX_HUNDRED_C",
    "FX_PICKUP_CENTENNIAL","FX_PICKUP_FULL","FX_PICKUP_FULLC","FX_PICKUP_TENT",
    "FX_PICKUP_C","FX_PICKUP_LETTERS","FX_PICKUP_LETTERC","FX_PICKUP_NEONC",
    "FX_NEON","FX_NEON_C","FX_PICKUP_NEON","FX_NEON_LETTER",
    "FX_PICKUP_GLOWING","FX_PICKUP_GLOW","FX_PICKUP_FLOAT","FX_PICKUP_HOVER",
    "FX_PICKUP_AIR","FX_PICKUP_FLOAT_C","FX_PICKUP_BOUNCE",
    "FX_TRIG","FX_TRIGGER","FX_PICKUP_TRIG","FX_PICKUP_TRIGGER",
    "FX_PICKUP_SECRET","FX_PICKUP_BONUS","FX_PICKUP_BONUSC","FX_PICKUP_FINAL",
    "FX_PICKUP_TROPHY","FX_PICKUP_MEDAL","FX_PICKUP_AWARD","FX_PICKUP_PRIZE",
    "FX_TROPHY","FX_MEDAL","FX_AWARD","FX_PRIZE","FX_GOLD","FX_PICKUP_GOLD",
    "FX_PICKUP_REWARD","FX_REWARD","FX_PICKUP_BANG","FX_BANG","FX_PICKUP_ZAP",
    "FX_PICKUP_ZINGER","FX_ZINGER","FX_TINGLE","FX_PICKUP_TINGLE",
    "FX_FLOATING_C","FX_C","FX_LETTER_C","FX_C_PICKUP","FX_C_GET","FX_C_GRAB",
    "FX_PICKUP_FREE_LIFE","FX_PICKUP_HEAD","FX_PICKUP_SPECIAL",
    "FX_DING","FX_DING_DONG","FX_DING_C","FX_DING_PICKUP","FX_DING_100",
    "FX_BING","FX_BING_C","FX_BLB_100","FX_BLB_C","FX_BLB_CENT",
    "FX_PICKUP_AURA","FX_PICKUP_HALO","FX_PICKUP_LIVELY","FX_PICKUP_SPRITE",
]

# 0x4a806042 - ClaySingle/Orb - "single piece of clay"
NAMES_CLAY = [
    "FX_PICKUP_CLAY","FX_PICKUP_CLAYBALL","FX_PICKUP_CLAY_BALL",
    "FX_PICKUP_ORB","FX_PICKUP_CLAYSINGLE","FX_PICKUP_CLAY_SINGLE",
    "FX_PICKUP_SINGLE","FX_PICKUP_BLB","FX_PICKUP_BLOB","FX_PICKUP_BALL",
    "FX_PICKUP_SHARD","FX_PICKUP_PIECE","FX_PICKUP_BIT","FX_PICKUP_CHUNK",
    "FX_PICKUP_NUGGET","FX_PICKUP_GIB","FX_PICKUP_GIBLET",
    "FX_PICKUP_DROPLET","FX_PICKUP_DROP","FX_PICKUP_GLOB","FX_PICKUP_DOLLOP",
    "FX_PICKUP_PILE","FX_PICKUP_STUFF","FX_PICKUP_GUNK","FX_PICKUP_MUCK",
    "FX_PICKUP_GOO","FX_PICKUP_OOZE","FX_PICKUP_SLIME","FX_PICKUP_MUD",
    "FX_PICKUP_CLAYDOH","FX_PICKUP_DOH","FX_PICKUP_BIGCLAY","FX_PICKUP_TINYCLAY",
    "FX_CLAY","FX_BLOB","FX_BLB","FX_BALL","FX_ORB","FX_SHARD","FX_PIECE","FX_BIT",
    "FX_CLAY_PICKUP","FX_CLAYBALL_PICKUP","FX_BLB_PICKUP","FX_ORB_PICKUP","FX_BALL_PICKUP",
    "FX_PICKUP_KLAYBALL","FX_PICKUP_KLAY","FX_PICKUP_KLAYBLOB","FX_PICKUP_KMAN",
    "FX_PICKUP_KMANBALL","FX_PICKUP_KMENBALL","FX_PICKUP_KMENBLOB",
    "FX_PICKUP_CLAY_ORB","FX_PICKUP_CLAYORB","FX_PICKUP_BLBSINGLE",
    "FX_PICKUP_BLB_SINGLE","FX_PICKUP_BLB_SHARD","FX_PICKUP_BLBSHARD",
    "FX_PICKUP_BLOBBIT","FX_PICKUP_BLOB_BIT","FX_PICKUP_BLBIT",
    "FX_PICKUP_SCRAP","FX_PICKUP_LUMP","FX_PICKUP_WAD","FX_PICKUP_DAB",
    "FX_PICKUP_BLOB_OF_CLAY","FX_PICKUP_LITTLE","FX_PICKUP_SMALL","FX_PICKUP_TINY",
    "FX_PICKUP_MINI","FX_PICKUP_MICRO","FX_PICKUP_MITE",
]

# Hamster names - try MORE patterns
NAMES_HAMSTER = [
    "FX_PICKUP_HAMSTERSHIELD","FX_PICKUP_HAMSTER_SHIELD","FX_PICKUP_HAMS",
    "FX_HAMSTERSHIELD","FX_HAMSTER_SHIELD","FX_HAMS","FX_HAMSTER",
    "FX_PICKUP_GERBIL","FX_PICKUP_GUINEA","FX_PICKUP_GUINEA_PIG","FX_PICKUP_GUINEAPIG",
    "FX_PICKUP_RODENT","FX_PICKUP_MOUSE","FX_PICKUP_MICE","FX_PICKUP_RAT","FX_PICKUP_RATS",
    "FX_PICKUP_FURBABY","FX_PICKUP_FUR_BABY","FX_PICKUP_TINYBALL","FX_PICKUP_TINY_BALL",
    "FX_PICKUP_FUZZBALL","FX_PICKUP_FUZZ_BALL","FX_PICKUP_FUZZER","FX_PICKUP_FUZZ",
    "FX_PICKUP_FURPET","FX_PICKUP_FURRYPET","FX_PICKUP_FURRY_PET",
    "FX_PICKUP_NIBBLES","FX_PICKUP_NIBBLER","FX_PICKUP_CHEWY","FX_PICKUP_FLUFFY",
    "FX_PICKUP_MINION","FX_PICKUP_MINIONS","FX_PICKUP_HELPER","FX_PICKUP_HELPERS",
    "FX_PICKUP_LIVE","FX_PICKUP_LIVES","FX_PICKUP_LIVING","FX_PICKUP_ANIMATED",
    "FX_PICKUP_BALL_OF_FUR","FX_PICKUP_BALLOFFUR",
    "FX_FUR","FX_FURRY","FX_FUZZY","FX_FUZZBALL","FX_FUZZ",
    "FX_HAM_SHIELD","FX_HAMSHIELD","FX_HAMSTER_SHLD","FX_HAMSHLD","FX_HAMSHEILD",
    "FX_PICKUP_HSHIELD","FX_PICKUP_H_SHIELD","FX_PICKUP_LITTLEFUR",
    "FX_PICKUP_AURA","FX_PICKUP_GUARD","FX_PICKUP_GUARDIAN","FX_PICKUP_PROTECT",
    "FX_PICKUP_PROTECTOR","FX_PICKUP_PROTECTORS","FX_PICKUP_SAVIOR",
    "FX_PICKUP_LIVELIVE","FX_PICKUP_LITTLES","FX_PICKUP_PALS","FX_PICKUP_PAL",
]

for tgt, label, cands in [(T, "100C/TriggerCollectible100C", NAMES_100C),
                          (T2, "ClaySingle/Orb pickup", NAMES_CLAY),
                          (T3, "HamsterShield regular", NAMES_HAMSTER),
                          (T4, "HamsterShield 3rd/full", [n + "_03" for n in NAMES_HAMSTER if "PICKUP" in n][:30] +
                                                          [n + "_FULL" for n in NAMES_HAMSTER if "PICKUP" in n][:30])]:
    print(f"\n=== 0x{tgt:08x} ({label}) ===")
    found = False
    for n in cands:
        h = calcHash(n)
        if h == tgt:
            print(f"  {n:35s} -> 0x{h:08x} <-- TARGET")
            found = True
    if not found:
        print(f"  No hit in {len(cands)} candidates")
