"""Verify 0x6082c120 = FX_PICKUP_BIRD/GLIDE/YELLOWBIRD/etc.
This is the Yellow Bird (Glidey) collectible pickup sound (grants glide).
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from calchash import calcHash

T = 0x6082c120
cands = [
    "FX_PICKUP_BIRD","FX_PICKUP_YELLOW","FX_PICKUP_YELLOWBIRD","FX_PICKUP_YELLOW_BIRD",
    "FX_PICKUP_GLIDE","FX_PICKUP_GLIDEY","FX_PICKUP_BIRDY","FX_PICKUP_BIRDIE",
    "FX_PICKUP_GLIDER","FX_PICKUP_FLY","FX_PICKUP_WING","FX_PICKUP_WINGS","FX_PICKUP_FLOAT",
    "FX_BIRD","FX_GLIDE","FX_GLIDEY","FX_YELLOWBIRD","FX_YELLOW_BIRD",
    "FX_BIRD_PICKUP","FX_BIRD_GRAB","FX_BIRD_GET","FX_GLIDE_PICKUP","FX_GLIDE_GRAB","FX_GLIDE_GET",
    "FX_PICKUP_BUDDY","FX_PICKUP_FRIEND","FX_PICKUP_PET",
    "FX_PICKUP_FLOATER","FX_PICKUP_HOVER","FX_PICKUP_SOAR",
    "FX_GLIDE_GAIN","FX_GLIDE_ON","FX_GLIDE_GET","FX_GLIDE_ACTIVATE",
    "FX_BIRD_ON","FX_BIRD_ACTIVATE","FX_BIRD_SPAWN","FX_BIRD_GAIN",
    "FX_PICKUP_FLOATY","FX_PICKUP_PUFFY","FX_PICKUP_PUFF",
    "FX_PICKUP_FLAP","FX_PICKUP_HOOT","FX_PICKUP_TWEET",
    "SFX_BIRD_PICKUP","SFX_BIRD","SFX_PICKUP_BIRD","SFX_PICKUP_GLIDE","SFX_GLIDE_PICKUP",
    "FX_PICKUP_BIRD_01","FX_PICKUP_GLIDE_01","FX_BIRD_PICKUP_01",
    "FX_BIRD_CHIME","FX_BIRD_CHIRP","FX_BIRD_TWEET","FX_BIRD_SONG",
    "FX_GLIDE_CHIME","FX_GLIDE_TWEET","FX_GLIDE_SONG",
    "FX_PICKUP_HALO","FX_PICKUP_FUR",
    "FX_GET_BIRD","FX_GET_GLIDE","FX_GAIN_BIRD","FX_GAIN_GLIDE",
    "FX_TAKE_BIRD","FX_TAKE_GLIDE","FX_GRAB_BIRD","FX_GRAB_GLIDE",
    "FX_NEW_BIRD","FX_NEW_GLIDE","FX_NEW_BUDDY","FX_NEW_PET",
    "FX_KLAY_BIRD","FX_KLAY_GLIDE","FX_KLAY_PICKUP","FX_KLAY_GLIDEY",
    "FX_GLIDEY","FX_BIRDIE","FX_BIRDY","FX_PICKUP","FX_PICKUP_01","FX_PICKUP_02",
    "FX_CHIME","FX_CHIME_01","FX_DING","FX_DING_DONG","FX_BIRD_HUH","FX_TWEET",
]

print(f"Target 0x6082c120 (Yellow Bird/Glidey pickup):")
for n in cands:
    h = calcHash(n)
    if h == T:
        print(f"  {n:30s} -> 0x{h:08x} <-- TARGET")
print(f"\nTried {len(cands)} candidates")
