"""Verify FX_PICKUP_SUPERWILLIE / etc for 0xe48744c4."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from calchash import calcHash

T = 0xe48744c4
print(f"Target 0x{T:08x} (Super Willie pickup):")
for n in [
    "FX_PICKUP_SUPERWILLIE","FX_PICKUP_SUPER_WILLIE","FX_PICKUP_WILLIE",
    "FX_PICKUP_SUPER","FX_PICKUP_SW","FX_PICKUP_TRANSFORM","FX_PICKUP_MORPH",
    "FX_SUPERWILLIE","FX_SUPER_WILLIE","FX_WILLIE","FX_SUPER","FX_SW",
    "FX_PICKUP_WILLY","FX_PICKUP_SUPER_WILLY","FX_SUPERWILLY","FX_SUPER_WILLY",
    "FX_PICKUP_TRANSFORM_01","FX_PICKUP_MORPH_01",
    "FX_PICKUP_MEGA","FX_PICKUP_BIG","FX_PICKUP_FORM","FX_PICKUP_NEWFORM",
    "FX_TRANSFORM","FX_MORPH","FX_NEWFORM","FX_FORM_CHANGE","FX_FORMCHANGE",
    "FX_TRANSFORM_GAIN","FX_TRANSFORM_PICKUP","FX_TRANSFORM_GET",
    "FX_PICKUP_PWR","FX_PICKUP_POWER","FX_PICKUP_BUFF","FX_PICKUP_UPGRADE",
    "FX_KLAY_SUPER","FX_KLAY_WILLIE","FX_KLAY_TRANSFORM","FX_KLAY_MORPH",
    "FX_TWIN","FX_TWINS","FX_BUDDIES","FX_DUO","FX_PARTNER",
    "FX_BLBS","FX_BLB_BUDDY","FX_BLB_PAIR","FX_BLB_TEAM",
]:
    h = calcHash(n)
    if h == T:
        print(f"  {n:35s} -> 0x{h:08x} <-- TARGET")
