"""Verify pickup sounds for Swirly, Phoenix Hand, Phart Head, Hamster Shield."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from calchash import calcHash

targets = {
    0x02847462: "Swirly-Q pickup",
    0x44c26454: "Phoenix Hand pickup",
    0xc0034658: "Phart Head pickup",
    0x42906465: "Hamster Shield pickup (regular)",
    0xc2906565: "Hamster Shield pickup (3rd/full)",
}

NAMES = {
    0x02847462: [
        "FX_PICKUP_SWIRLY","FX_PICKUP_SWIRLYQ","FX_PICKUP_SWIRLY_Q",
        "FX_PICKUP_Q","FX_PICKUP_QU","FX_SWIRLY","FX_SWIRLYQ","FX_SWIRLY_Q",
        "FX_PICKUP_SQ","FX_PICKUP_S","FX_SQ","FX_S","FX_PICKUP_O","FX_PICKUP_LIFE",
        "FX_PICKUP_EXTRA","FX_PICKUP_EXTRA_LIFE","FX_PICKUP_1UP","FX_PICKUP_1_UP",
        "FX_PICKUP_BONUS","FX_PICKUP_FOUR_LEAF","FX_PICKUP_LUCKY",
        "FX_PICKUP_TOKEN","FX_PICKUP_COIN","FX_PICKUP_GEM","FX_PICKUP_STAR",
        "FX_PICKUP_ICON","FX_PICKUP_RING","FX_PICKUP_HEART","FX_PICKUP_ORB",
        "FX_PICKUP_BLB","FX_PICKUP_BUDDY","FX_PICKUP_ITEM","FX_PICKUP_LIFE_01",
        "SFX_SWIRLY","FX_SWIRL","FX_SPIN","FX_TWIRL","FX_TWIST",
        "FX_PICKUP_TWIRL","FX_PICKUP_SPIN","FX_PICKUP_TWIST",
        "FX_BLB_PICKUP","FX_PICKUP_BLB_Q","FX_PICKUP_QBALL",
        "FX_PICKUP_LETTERQ","FX_PICKUP_KLAYMENQ",
        "FX_PICKUP","FX_GRAB","FX_GRAB_01","FX_GRAB_02",
    ],
    0x44c26454: [
        "FX_PICKUP_PHOENIX","FX_PICKUP_PHOENIX_HAND","FX_PICKUP_PHOENIXHAND",
        "FX_PICKUP_HAND","FX_PICKUP_HANDS","FX_PICKUP_FIRE","FX_PICKUP_FIREHAND",
        "FX_PHOENIX","FX_PHOENIX_HAND","FX_PHOENIXHAND","FX_HAND","FX_HANDS",
        "FX_PICKUP_FIST","FX_PICKUP_PUNCH","FX_PICKUP_BURN","FX_PICKUP_PROJECTILE",
        "FX_PICKUP_AMMO","FX_PICKUP_SHOOT","FX_PICKUP_RANGE","FX_PICKUP_THROW",
        "FX_PICKUP_PROJ","FX_PICKUP_FLAME","FX_PICKUP_FX",
        "FX_PHOENIX_PICKUP","FX_PHX_PICKUP","FX_PICKUP_PHX",
        "FX_FIST","FX_BIRD","FX_PHOENIXBIRD","FX_PICKUP_PHOENIXBIRD",
        "FX_PICKUP_RED","FX_PICKUP_HOT","FX_PICKUP_FIERY","FX_PICKUP_LASER",
        "FX_PICKUP_BULLET","FX_PICKUP_GUN","FX_PICKUP_BLAST","FX_PICKUP_BANG",
        "FX_PICKUP_PEW","FX_PICKUP_ZAP",
    ],
    0xc0034658: [
        "FX_PICKUP_PHART","FX_PICKUP_PHARTHEAD","FX_PICKUP_PHART_HEAD",
        "FX_PICKUP_HEAD","FX_PICKUP_HEADS","FX_PICKUP_GIB","FX_PICKUP_GIBLET",
        "FX_PHART","FX_PHART_HEAD","FX_PHARTHEAD","FX_PHARTHEADS","FX_PHARTS",
        "FX_PICKUP_FART","FX_PICKUP_FARTHEAD","FX_FARTHEAD","FX_FART_HEAD",
        "FX_HEAD","FX_HEADS","FX_GIB","FX_GIBLET","FX_GIBLETS",
        "FX_PICKUP_SKULL","FX_SKULL_PICKUP","FX_PICKUP_HP","FX_PICKUP_HEALTH",
        "FX_PICKUP_LIFE","FX_PICKUP_BLOOD","FX_PICKUP_CHUNK","FX_PICKUP_BIT",
        "FX_PICKUP_FRAG","FX_PICKUP_PIECE","FX_PICKUP_PART","FX_PICKUP_BONE",
        "FX_PICKUP_TRINKET","FX_PICKUP_TROPHY","FX_PICKUP_MEDAL",
    ],
    0x42906465: [
        "FX_PICKUP_HAMSTER","FX_PICKUP_HAMSTER_SHIELD","FX_PICKUP_SHIELD_HAMSTER",
        "FX_HAMSTER","FX_HAMSTER_SHIELD","FX_PICKUP_HAM","FX_PICKUP_HAMS",
        "FX_PICKUP_FURRY","FX_PICKUP_FUR","FX_PICKUP_FUZZY","FX_PICKUP_PET","FX_PICKUP_FRIEND",
        "FX_PICKUP_BUDDY","FX_PICKUP_FUR_BALL","FX_PICKUP_ANIMAL","FX_PICKUP_CRITTER",
        "FX_PICKUP_HAMSTER_01","FX_PICKUP_HAMSTER_NORM","FX_PICKUP_HAMSTER_REG",
        "FX_HAM","FX_FURRY","FX_FUZZY","FX_FUR","FX_BUDDY","FX_PET",
        "FX_PICKUP_HALO","FX_PICKUP_RING","FX_PICKUP_AURA",
        "FX_PICKUP_ORB","FX_PICKUP_ORBIT","FX_PICKUP_SAT","FX_PICKUP_SATELLITE",
    ],
    0xc2906565: [
        "FX_PICKUP_HAMSTER_03","FX_PICKUP_HAMSTER_3","FX_PICKUP_HAMSTER_FULL",
        "FX_PICKUP_HAMSTER_MAX","FX_PICKUP_HAMSTER_3RD","FX_PICKUP_HAMSTER_LAST",
        "FX_HAMSTER_03","FX_HAMSTER_3","FX_HAMSTER_FULL","FX_HAMSTER_MAX","FX_HAMSTER_3RD",
        "FX_PICKUP_HAM_03","FX_PICKUP_HAM_3","FX_PICKUP_HAM_FULL","FX_PICKUP_HAM_MAX",
        "FX_PICKUP_HAMSTER_DONE","FX_PICKUP_HAMSTER_END","FX_PICKUP_HAMSTER_PEAK",
        "FX_PICKUP_FURRY_03","FX_PICKUP_FUR_03","FX_PICKUP_FUR_FULL",
        "FX_PICKUP_HAMSTER_ALL","FX_PICKUP_HAMSTER_TOP",
        "FX_GAIN_HAMSTER","FX_GAIN_SHIELD",
    ],
}

for t, label in targets.items():
    print(f"\nTarget 0x{t:08x} ({label}):")
    found = False
    for n in NAMES[t]:
        h = calcHash(n)
        if h == t:
            print(f"  {n:35s} -> 0x{h:08x} <-- TARGET")
            found = True
    if not found:
        print(f"  No hit out of {len(NAMES[t])} candidates")
