/* =============================================================================
 * clayball.rodata.c  --  faithful C reproduction of asm/data/clayball.rodata.s
 * -----------------------------------------------------------------------------
 * GENERATED by tools/gen_port_data.py -- do not edit by hand.
 * Pointer tables (entity/render vtables) transcribed word-for-word with the
 * original symbol references; the linker binds each to the port's converted or
 * weak-stub function, exactly as the MIPS byte-match linker resolves the
 * `.word Symbol` entries. Targets are declared opaque (extern char SYM[]) so
 * address-of never conflicts with the real prototype in functions.h.
 * ========================================================================== */

extern char EntityDestroyCallback_Vt800116E8[];
extern char EntityDestroyCallback_Vt800116E8_800594a0[];
extern char EntityDestroyCallback_Vt800116E8_80059504[];
extern char EntityDestroyCallback_Vt800116E8_80059568[];
extern char EntityDestroyCallback_Vt800116E8_800595cc[];
extern char EntityDestroy_SmallClayballHelper[];
extern char EntityDestructor_FreeResourceAt24[];
extern char EntityDestructor_WithChildEntityCleanup[];
extern char EntityDestructor_WithSPUVoiceStop[];
extern char FinnDispatchGsEventOnFlag[];
extern char FinnNoopCallback_8006ED44[];
extern char FinnNoopCallback_8006ED4C[];
extern char FinnRenderCallback_ProjectToScreen[];
extern char FinnSubentityDestroyCallback_Simple[];
extern char FinnSubentityDestroyCallback_Vtable0x80011784[];
extern char FinnSubentityDestroyCallback_Vtable0x800117c4[];
extern char FinnSubentityDestroyCallback_Vtable0x800117e4[];
extern char ShrineyGuardDestroyWithSoundCleanup[];
extern char UpdateEntityRender[];
extern char UploadEntityTextureIfDirty[];
extern char func_80059630[];
extern char func_80059638[];

void *D_80011628[8] = {
    0,
    0,
    0,
    (void *)ShrineyGuardDestroyWithSoundCleanup,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011648[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800116E8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011668[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800116E8_800594a0,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011688[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800116E8_80059504,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800116A8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800116E8_80059568,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800116C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_WithChildEntityCleanup,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800116E8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800116E8_800595cc,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011708[8] = {
    0,
    0,
    0,
    (void *)EntityDestroy_SmallClayballHelper,
    0,
    (void *)func_80059638,
    0,
    (void *)func_80059630
};

/* MIPS switch jump table (19 entries) -- code labels are
 * meaningless on PC; zeroed placeholder keeps the symbol strong. */
void *jtbl_80011728[19];

char g_FntFmt_StagePos[] = "%d:(%d,%d)\n";

void *D_80011784[8] = {
    0,
    0,
    0,
    (void *)FinnSubentityDestroyCallback_Vtable0x80011784,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800117A4[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeResourceAt24,
    0,
    (void *)FinnRenderCallback_ProjectToScreen,
    0,
    (void *)FinnDispatchGsEventOnFlag
};

void *D_800117C4[8] = {
    0,
    0,
    0,
    (void *)FinnSubentityDestroyCallback_Vtable0x800117c4,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800117E4[8] = {
    0,
    0,
    0,
    (void *)FinnSubentityDestroyCallback_Vtable0x800117e4,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *g_PlayerCallbackTable[16] = {
    0,
    0,
    0,
    (void *)EntityDestructor_WithSPUVoiceStop,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    0,
    0,
    (void *)FinnSubentityDestroyCallback_Simple,
    0,
    (void *)FinnNoopCallback_8006ED4C,
    0,
    (void *)FinnNoopCallback_8006ED44
};
