/* =============================================================================
 * gfx.rodata.c  --  faithful C reproduction of asm/data/gfx.rodata.s
 * -----------------------------------------------------------------------------
 * GENERATED by tools/gen_port_data.py -- do not edit by hand.
 * Pointer tables (entity/render vtables) transcribed word-for-word with the
 * original symbol references; the linker binds each to the port's converted or
 * weak-stub function, exactly as the MIPS byte-match linker resolves the
 * `.word Symbol` entries. Targets are declared opaque (extern char SYM[]) so
 * address-of never conflicts with the real prototype in functions.h.
 * ========================================================================== */

/* UNRESOLVED mid-function label 0x80025920 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80025920(void) {}
/* UNRESOLVED mid-function label 0x80025928 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80025928(void) {}

extern char DestroyEntity[];
extern char DestroyEntityAndFreeMemory[];
extern char EntityDestructor_DestroyAllChildEntities[];
extern char EntityDestructor_FreeMultiAlloc[];
extern char EntityDestructor_FreeResourceType2[];
extern char EntityDestructor_FreeResourceType3[];
extern char EntityDestructor_FreeWithChildRef[];
extern char EntityDestructor_RemoveFromRenderList[];
extern char EntityDestructor_Simple[];
extern char EntityDestructor_Simple2[];
extern char EntityDestructor_Type0[];
extern char EntityDestructor_Type1[];
extern char EntityDestructor_Type2[];
extern char EntityDestructor_Type3[];
extern char EntityDestructor_Type4[];
extern char EntityDestructor_Type5[];
extern char EntityDestructor_Type6_Simple[];
extern char EntityRemoval[];
extern char FreeResourceType4[];
extern char FreeTextureResource[];
extern char FreeWithCallback[];
extern char MenuEntityDestroyCallback[];
extern char NopStub_800207d4[];
extern char NopStub_800207dc[];
extern char RenderSpriteOrScaledQuad[];
extern char RenderTilemapLayerWithScroll[];
extern char RenderTilemapPrimitivesWithBounds[];
extern char RenderTilemapWithWrapAround[];
extern char SubmitPrimitiveBufferToGPU[];
extern char TriggerFadeTransition[];
extern char UpdateEntityRender[];
extern char UpdateEntityScreenPosition[];
extern char UpdateParallaxLayerPosition[];
extern char UploadEntityTextureIfDirty[];
extern char func_80018D4C[];
extern char func_8001B344[];
extern char func_8002C794[];
extern char func_8002C79C[];

void *D_80010324[8] = {
    (void *)0x1000,
    0,
    (void *)0x1000,
    0,
    (void *)0x1000,
    0,
    0,
    0
};

void *D_80010344[4] = {
    0,
    0,
    0,
    (void *)SubmitPrimitiveBufferToGPU
};

void *D_80010354[4] = {
    0,
    0,
    0,
    (void *)RenderTilemapWithWrapAround
};

void *D_80010364[4] = {
    0,
    0,
    0,
    (void *)RenderTilemapPrimitivesWithBounds
};

void *D_80010374[4] = {
    0,
    0,
    0,
    (void *)RenderTilemapLayerWithScroll
};

void *D_80010384[6] = {
    0,
    0,
    0,
    (void *)RenderSpriteOrScaledQuad,
    0,
    (void *)FreeTextureResource
};

void *D_8001039C[4] = {
    0,
    0,
    0,
    (void *)func_80018D4C
};

void *D_800103AC[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeWithChildRef,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *g_EntityVtable_ResourceType4[8] = {
    0,
    0,
    0,
    (void *)FreeResourceType4,
    0,
    (void *)UpdateEntityScreenPosition,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_ResourceType3[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeResourceType3,
    0,
    (void *)NopStub_800207dc,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_ResourceType2[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeResourceType2,
    0,
    (void *)NopStub_800207dc,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_ResourceType1[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeMultiAlloc,
    0,
    (void *)NopStub_800207dc,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_SpriteBase[8] = {
    0,
    0,
    0,
    (void *)DestroyEntityAndFreeMemory,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *g_EntityVtable_PartialDestroy[8] = {
    0,
    0,
    0,
    (void *)FreeWithCallback,
    0,
    (void *)UpdateParallaxLayerPosition,
    0,
    (void *)func_8001B344
};

void *D_8001048C[8] = {
    0,
    0,
    0,
    (void *)MenuEntityDestroyCallback,
    0,
    (void *)NopStub_800207dc,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_Destroyed[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Simple,
    0,
    (void *)NopStub_800207dc,
    0,
    (void *)NopStub_800207d4
};

void *g_EntityVtable_SimpleDestruct[8] = {
    0,
    0,
    0,
    (void *)DestroyEntity,
    0,
    (void *)unresolved_80025928  /* UNRESOLVED 0x80025928 */,
    0,
    (void *)EntityRemoval
};

void *g_EntityVtable_LevelDestroy[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Simple2,
    0,
    (void *)unresolved_80025928  /* UNRESOLVED 0x80025928 */,
    0,
    (void *)unresolved_80025920  /* UNRESOLVED 0x80025920 */
};

void *D_8001050C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_DestroyAllChildEntities,
    0,
    (void *)func_8002C79C,
    0,
    (void *)func_8002C794
};

void *D_8001052C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_RemoveFromRenderList,
    0,
    (void *)func_8002C79C,
    0,
    (void *)TriggerFadeTransition
};

void *D_8001054C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type0,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_8001056C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type1,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_8001058C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type2,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800105AC[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type3,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800105CC[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type4,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800105EC[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type5,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_8001060C[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Type6_Simple,
    0,
    (void *)func_8002C79C,
    0,
    (void *)func_8002C794
};
