/* =============================================================================
 * hud.rodata.c  --  faithful C reproduction of asm/data/hud.rodata.s
 * -----------------------------------------------------------------------------
 * GENERATED by tools/gen_port_data.py -- do not edit by hand.
 * Pointer tables (entity/render vtables) transcribed word-for-word with the
 * original symbol references; the linker binds each to the port's converted or
 * weak-stub function, exactly as the MIPS byte-match linker resolves the
 * `.word Symbol` entries. Targets are declared opaque (extern char SYM[]) so
 * address-of never conflicts with the real prototype in functions.h.
 * ========================================================================== */

extern char BeamEffectDespawnEvent[];
extern char BeamEffectRenderCallback[];
extern char CalculateChildEntityRenderPos[];
extern char DestroyCompoundEntity[];
extern char DestroyEntityWithChildRemoval[];
extern char DestroyEntityWithData[];
extern char DestroyEntityWithSoundAndChild[];
extern char DestroyGridDistortionEffect[];
extern char DestroyOscillatingScaleEntity[];
extern char DestroyPathFollowEntity[];
extern char DestroyRippleExpandEffect[];
extern char DestroySoundEmitterEntity[];
extern char DestroySoundEntity[];
extern char DestroySoundEntityWithVoice[];
extern char DestroySpotlightBeamEffect[];
extern char DestroyTimedFadeEntity[];
extern char DispatchGsEventOnFlag34[];
extern char EnemyDestroyCallback_0x80011228[];
extern char EntityDespawnIfFlagSet[];
extern char EntityDestroyCallback_Vt80010A48[];
extern char EntityDestroyCallback_Vt80010A68[];
extern char EntityDestroyCallback_Vt80010B28[];
extern char EntityDestroyCallback_Vt80010BA8[];
extern char EntityDestroyCallback_Vt80010BA8_80038510[];
extern char EntityDestroyCallback_Vt80010BA8_80038904[];
extern char EntityDestroyCallback_Vt80010BC8[];
extern char EntityDestroyCallback_Vt80010C64[];
extern char EntityDestroyCallback_Vt80010DE4[];
extern char EntityDestroyCallback_Vt80010DE4_800410bc[];
extern char EntityDestroyCallback_Vt80010DE4_80041120[];
extern char EntityDestroyCallback_Vt80010DE4_800411cc[];
extern char EntityDestroyCallback_Vt80010DE4_80041230[];
extern char EntityDestroyCallback_Vt80010DE4_80041294[];
extern char EntityDestroyCallback_Vt80010DE4_800412f8[];
extern char EntityDestroyCallback_Vt80010DE4_8004135c[];
extern char EntityDestroyCallback_Vt80010DE4_800413c0[];
extern char EntityDestroyCallback_Vt80010E04[];
extern char EntityDestroyCallback_Vt80010E04_80041434[];
extern char EntityDestroyCallback_Vt80011068[];
extern char EntityDestroyCallback_Vt80011088[];
extern char EntityDestroyCallback_Vt800110A8[];
extern char EntityDestroyCallback_Vt800110E8[];
extern char EntityDestroyCallback_Vt80011108[];
extern char EntityDestroyCallback_Vt80011128[];
extern char EntityDestroyCallback_Vt80011148[];
extern char EntityDestroyCallback_Vt80011168[];
extern char EntityDestroyCallback_Vt80011188[];
extern char EntityDestroyCallback_Vt800111C8[];
extern char EntityDestroyCallback_Vt800111C8_80045e80[];
extern char EntityDestroyCallback_Vt80011228[];
extern char EntityDestroyCallback_Vt80011248[];
extern char EntityDestroyCallback_Vt800113C8[];
extern char EntityDestroyCallback_Vt800113E8[];
extern char EntityDestroyCallback_Vt80011408[];
extern char EntityDestroyCallback_Vt80011428[];
extern char EntityDestroyCallback_Vt80011488[];
extern char EntityDestroyCallback_Vt800114A8[];
extern char EntityDestroyCallback_Vt800114C8[];
extern char EntityDestroyCallback_Vt800114E8[];
extern char EntityDestroyCallback_Vt80011508[];
extern char EntityDestroyCallback_Vt80011548[];
extern char EntityDestroyCallback_Vt80011568[];
extern char EntityDestroyCallback_Vt80011588[];
extern char EntityDestroyCallback_Vt800115C8[];
extern char EntityDestroyCallback_Vt800115E8[];
extern char EntityDestroyCallback_Vt800115E8_800556b8[];
extern char EntityDestroyCallback_Vt80011608[];
extern char EntityDestroyResourceType4[];
extern char EntityDestroyWithFreeCallback1[];
extern char EntityDestroyWithFreeCallback2[];
extern char EntityDestroyWithFreeCallback3[];
extern char EntityDestroyWithFreeCallback4[];
extern char EntityDestructor_FreeRenderListAt120[];
extern char EntityDestructor_Vtable0x80010870_A[];
extern char EntityDestructor_Vtable0x80010870_B[];
extern char EntityDestructor_Vtable0x80010870_C[];
extern char EntityDestructor_Vtable0x80010870_D[];
extern char EntityDestructor_Vtable0x80010870_E[];
extern char EntityDestructor_Vtable0x80010870_F[];
extern char EntityDestructor_Vtable0x80010870_G[];
extern char EntityDestructor_Vtable0x80010870_H[];
extern char EntityDestructor_Vtable0x80010870_I[];
extern char EntityDestructor_Vtable0x80010870_J[];
extern char EntityDestructor_Vtable0x80010870_K[];
extern char EntityDestructor_Vtable0x80010870_L[];
extern char EntityDestructor_Vtable0x80010870_M[];
extern char EntityDestructor_Vtable0x80010870_N[];
extern char EntityDestructor_Vtable0x80010870_O[];
extern char EntityDestructor_Vtable0x80010870_P[];
extern char EntityDestructor_Vtable0x80010870_Q[];
extern char EntityDestructor_VtableAndHeapFree[];
extern char EntityDestructor_WithSPUVoiceStopAndClear[];
extern char EntityDestructor_WithTextureAndMemory[];
extern char EntityDestructor_WithVRAMSlotFree[];
extern char EntityRenderCallbackUpdateScreenPos[];
extern char EntityRenderWithScaledPosition[];
extern char EntityTick_UploadTextureWithCallback[];
extern char ExpiredEntityDespawnEvent[];
extern char FadeExpireEntityDespawnEvent[];
extern char FlushDepthBucketsGlobal[];
extern char GenericEntityDestroyCallback[];
extern char JoeHeadJoeBossDestructor[];
extern char JoeHeadJoeDestroyCallback[];
extern char KloggDestroyCallback[];
extern char MonkeyMageAuxDestroyCallback[];
extern char MonkeyMageBossPartDestroyCallback[];
extern char MonkeyMageDestroyCallback[];
extern char MonkeyMageForceFieldDestroyCallback[];
extern char MonkeyMageHUDDestroyCallback[];
extern char MonkeyMagePartDestroyCallback[];
extern char MonkeyMagePlatformDestroyCallback[];
extern char MonkeyMageSimpleDestroyCallback[];
extern char MultiPartEntityRenderTick[];
extern char NopStub_80038968[];
extern char NopStub_80038970[];
extern char NopStub_80041424[];
extern char NopStub_8004142c[];
extern char NopStub_80045e70[];
extern char NopStub_80045e78[];
extern char NopStub_80046ce4[];
extern char NopStub_80046cec[];
extern char NopStub_8005571c[];
extern char NopStub_80055724[];
extern char RenderFullScreenTileOverlay[];
extern char RenderGridDistortionEffect[];
extern char RenderPathEntitySegments[];
extern char RenderRippleExpandEffect[];
extern char RenderRopeSegments[];
extern char RenderRotatedTexturedQuad[];
extern char RenderSpotlightBeamEffect[];
extern char RenderVRAMSlotOverlay[];
extern char Render_RotatingStarEffect[];
extern char RippleEffectRenderCallback[];
extern char SoundEmitterDestroyCallback[];
extern char SoundEntityDestroyCallback[];
extern char UpdateAndUploadSpriteToVRAM[];
extern char UpdateEntityRender[];
extern char UpdateEntityScreenPosition[];
extern char UpdateParallaxLayerPosition[];
extern char UploadEntityTextureIfDirty[];
extern char func_8002D978[];
extern char func_80030C98[];
extern char func_80030CA0[];
extern char func_8004F024[];
extern char func_8004F02C[];

/* MIPS switch jump table (9 entries) -- code labels are
 * meaningless on PC; zeroed placeholder keeps the symbol strong. */
void *jtbl_8001062C[9];

void *D_80010650[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_A,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010670[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_VtableAndHeapFree,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010690[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_B,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800106B0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_C,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800106D0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_D,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800106F0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_E,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010710[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_F,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010730[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_G,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010750[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_H,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010770[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_I,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010790[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_J,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800107B0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_K,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800107D0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_L,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800107F0[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_M,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010810[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_N,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010830[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_FreeRenderListAt120,
    0,
    (void *)EntityRenderWithScaledPosition,
    0,
    (void *)func_8002D978
};

void *D_80010850[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_O,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010870[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_P,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010890[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_Vtable0x80010870_Q,
    0,
    (void *)func_80030CA0,
    0,
    (void *)func_80030C98
};

void *D_800108B0[8] = {
    (void *)0x1000,
    0,
    (void *)0x1000,
    0,
    (void *)0x1000,
    0,
    0,
    0
};

void *D_800108D0[8] = {
    0,
    0,
    0,
    (void *)DestroyTimedFadeEntity,
    0,
    (void *)NopStub_80038970,
    0,
    (void *)NopStub_80038968
};

void *D_800108F0[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010BA8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010910[8] = {
    0,
    0,
    0,
    (void *)DestroyOscillatingScaleEntity,
    0,
    (void *)NopStub_80038970,
    0,
    (void *)FadeExpireEntityDespawnEvent
};

void *D_80010930[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010BA8_80038510,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010950[8] = {
    0,
    0,
    0,
    (void *)DestroySpotlightBeamEffect,
    0,
    (void *)BeamEffectRenderCallback,
    0,
    (void *)BeamEffectDespawnEvent
};

void *D_80010970[4] = {
    0,
    0,
    0,
    (void *)RenderSpotlightBeamEffect
};

void *D_80010980[8] = {
    0,
    0,
    0,
    (void *)DestroyRippleExpandEffect,
    0,
    (void *)RippleEffectRenderCallback,
    0,
    (void *)ExpiredEntityDespawnEvent
};

void *D_800109A0[4] = {
    0,
    0,
    0,
    (void *)RenderRippleExpandEffect
};

void *D_800109B0[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyWithFreeCallback1,
    0,
    (void *)UpdateParallaxLayerPosition,
    0,
    (void *)UpdateAndUploadSpriteToVRAM
};

void *D_800109D0[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyWithFreeCallback2,
    0,
    (void *)UpdateParallaxLayerPosition,
    0,
    (void *)UpdateAndUploadSpriteToVRAM
};

void *D_800109F0[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyWithFreeCallback3,
    0,
    (void *)UpdateParallaxLayerPosition,
    0,
    (void *)UpdateAndUploadSpriteToVRAM
};

void *D_80010A10[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyWithFreeCallback4,
    0,
    (void *)UpdateParallaxLayerPosition,
    0,
    (void *)EntityDespawnIfFlagSet
};

void *D_80010A30[6] = {
    0,
    0,
    0,
    (void *)RenderGridDistortionEffect,
    0,
    (void *)DestroyGridDistortionEffect
};

void *D_80010A48[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010A48,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010A68[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010A68,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010A88[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyResourceType4,
    0,
    (void *)UpdateEntityScreenPosition,
    0,
    (void *)DispatchGsEventOnFlag34
};

void *D_80010AA8[4] = {
    0,
    0,
    0,
    (void *)RenderFullScreenTileOverlay
};

void *D_80010AB8[8] = {
    0,
    0,
    0,
    (void *)DestroyCompoundEntity,
    0,
    (void *)CalculateChildEntityRenderPos,
    0,
    (void *)EntityTick_UploadTextureWithCallback
};

void *D_80010AD8[4] = {
    0,
    0,
    0,
    (void *)FlushDepthBucketsGlobal
};

void *D_80010AE8[6] = {
    0,
    0,
    0,
    (void *)RenderRopeSegments,
    0,
    (void *)EntityDestructor_WithTextureAndMemory
};

void *D_80010B00[6] = {
    0,
    0,
    0,
    (void *)RenderPathEntitySegments,
    0,
    (void *)DestroyPathFollowEntity
};

void *D_80010B18[4] = {
    0,
    0,
    0,
    (void *)Render_RotatingStarEffect
};

void *D_80010B28[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010B28,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010B48[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_WithVRAMSlotFree,
    0,
    (void *)EntityRenderCallbackUpdateScreenPos,
    0,
    (void *)MultiPartEntityRenderTick
};

void *D_80010B68[4] = {
    0,
    0,
    0,
    (void *)RenderVRAMSlotOverlay
};

void *D_80010B78[8] = {
    0,
    0,
    0,
    (void *)DestroyEntityWithData,
    0,
    (void *)NopStub_80038970,
    0,
    (void *)NopStub_80038968
};

void *D_80010B98[4] = {
    0,
    0,
    0,
    (void *)RenderRotatedTexturedQuad
};

void *D_80010BA8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010BA8_80038904,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010BC8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010BC8,
    0,
    (void *)NopStub_80038970,
    0,
    (void *)NopStub_80038968
};

char D_80010BE8[] = "\\GAME.BLB;1";

char D_80010BF4[] = "\\MUSIC1.XA;1";

char D_80010C04[] = "\\MUSIC2.XA;1";

char D_80010C14[] = "\\MUSIC3.XA;1";

char D_80010C24[] = "\\MUSIC4.XA;1";

char D_80010C34[] = "\\MUSIC5.XA;1";

void *D_80010C44[8] = {
    0,
    0,
    0,
    (void *)DestroyEntityWithSoundAndChild,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010C64[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010C64,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010C84[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010CA4[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_800410bc,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010CC4[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_80041120,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010CE4[8] = {
    0,
    0,
    0,
    (void *)DestroySoundEntityWithVoice,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010D04[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010E04,
    0,
    (void *)NopStub_8004142c,
    0,
    (void *)NopStub_80041424
};

void *D_80010D24[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_800411cc,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010D44[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_80041230,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010D64[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_80041294,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010D84[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_800412f8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010DA4[8] = {
    0,
    0,
    0,
    (void *)DestroySoundEmitterEntity,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010DC4[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_8004135c,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010DE4[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010DE4_800413c0,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80010E04[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80010E04_80041434,
    0,
    (void *)NopStub_8004142c,
    0,
    (void *)NopStub_80041424
};

/* MIPS switch jump table (118 entries) -- code labels are
 * meaningless on PC; zeroed placeholder keeps the symbol strong. */
void *jtbl_80010E24[118];

/* MIPS switch jump table (19 entries) -- code labels are
 * meaningless on PC; zeroed placeholder keeps the symbol strong. */
void *jtbl_80010FFC[19];

void *D_80011048[8] = {
    0,
    0,
    0,
    (void *)SoundEmitterDestroyCallback,
    0,
    (void *)NopStub_80045e78,
    0,
    (void *)NopStub_80045e70
};

void *D_80011068[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011068,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011088[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011088,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800110A8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800110A8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800110C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800111C8,
    0,
    (void *)NopStub_80045e78,
    0,
    (void *)NopStub_80045e70
};

void *D_800110E8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800110E8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011108[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011108,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011128[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011128,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011148[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011148,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011168[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011168,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011188[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011188,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800111A8[8] = {
    0,
    0,
    0,
    (void *)DestroyEntityWithChildRemoval,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800111C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800111C8_80045e80,
    0,
    (void *)NopStub_80045e78,
    0,
    (void *)NopStub_80045e70
};

void *D_800111E8[8] = {
    0,
    0,
    0,
    (void *)SoundEntityDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011208[8] = {
    0,
    0,
    0,
    (void *)EnemyDestroyCallback_0x80011228,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011228[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011228,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011248[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011248,
    0,
    (void *)NopStub_80046cec,
    0,
    (void *)NopStub_80046ce4
};

void *D_80011268[8] = {
    0,
    0,
    0,
    (void *)KloggDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011288[8] = {
    0,
    0,
    0,
    (void *)JoeHeadJoeBossDestructor,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800112A8[8] = {
    0,
    0,
    0,
    (void *)MonkeyMagePartDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800112C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_WithSPUVoiceStopAndClear,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800112E8[8] = {
    0,
    0,
    0,
    (void *)MonkeyMagePlatformDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011308[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011328[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageForceFieldDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011348[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageAuxDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011368[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageBossPartDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011388[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageHUDDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800113A8[8] = {
    0,
    0,
    0,
    (void *)MonkeyMageSimpleDestroyCallback,
    0,
    (void *)func_8004F02C,
    0,
    (void *)func_8004F024
};

void *D_800113C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800113C8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800113E8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800113E8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011408[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011408,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011428[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011428,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011448[8] = {
    0,
    0,
    0,
    (void *)JoeHeadJoeDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011468[8] = {
    0,
    0,
    0,
    (void *)DestroySoundEntity,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011488[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011488,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800114A8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800114A8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800114C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800114C8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800114E8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800114E8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011508[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011508,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011528[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800115E8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011548[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011548,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011568[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011568,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011588[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011588,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800115A8[8] = {
    0,
    0,
    0,
    (void *)GenericEntityDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800115C8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800115C8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800115E8[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt800115E8_800556b8,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011608[8] = {
    0,
    0,
    0,
    (void *)EntityDestroyCallback_Vt80011608,
    0,
    (void *)NopStub_80055724,
    0,
    (void *)NopStub_8005571c
};
