/* =============================================================================
 * vehicle.rodata.c  --  faithful C reproduction of asm/data/vehicle.rodata.s
 * -----------------------------------------------------------------------------
 * GENERATED by tools/gen_port_data.py -- do not edit by hand.
 * Pointer tables (entity/render vtables) transcribed word-for-word with the
 * original symbol references; the linker binds each to the port's converted or
 * weak-stub function, exactly as the MIPS byte-match linker resolves the
 * `.word Symbol` entries. Targets are declared opaque (extern char SYM[]) so
 * address-of never conflicts with the real prototype in functions.h.
 * ========================================================================== */

/* UNRESOLVED mid-function label 0x800732c4 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_800732c4(void) {}
/* UNRESOLVED mid-function label 0x800732cc (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_800732cc(void) {}
/* UNRESOLVED mid-function label 0x8007408c (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_8007408c(void) {}
/* UNRESOLVED mid-function label 0x80074094 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80074094(void) {}
/* UNRESOLVED mid-function label 0x80074f24 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80074f24(void) {}
/* UNRESOLVED mid-function label 0x80074f2c (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80074f2c(void) {}
/* UNRESOLVED mid-function label 0x80079d88 (splat left it un-named);
 * faithful behaviour is a bare return. */
static void unresolved_80079d88(void) {}

extern char EndingEntityDestroyCallback_1E54[];
extern char EndingEntityDestroyCallback_1E74[];
extern char EndingEntityDestroyCallback_2034[];
extern char EndingEntityDestroyCallback_2034_V2[];
extern char EndingEntityDestroyCallback_2034_V3[];
extern char EndingEntityDestroyCallback_2034_V4[];
extern char EndingEntityDestroyCallback_2034_V5[];
extern char EndingEntityDestroyCallback_208C[];
extern char EndingEntityDestroyCallback_20AC[];
extern char EndingEntityDestroyCallback_20CC[];
extern char EndingNoopCallback_80079dec[];
extern char EndingNoopCallback_80079f90[];
extern char EndingNoopCallback_80079f98[];
extern char EndingNoopCallback_80079fa0[];
extern char EndingNoopCallback_80079fa8[];
extern char EndingNoopCallback_8007a0dc[];
extern char EndingNoopCallback_8007a0e4[];
extern char EntityDestructor_WithSPUStopAndFree[];
extern char FINN_ClearSubentityState[];
extern char FinnDestroyCallback_Simple[];
extern char FinnDestroyCallback_Vtable0x80011e34[];
extern char FinnDestroyWithSoundCleanup[];
extern char MenuActivateButton[];
extern char MenuActivateButtonWithReset[];
extern char MenuActivateLevelSelectButton[];
extern char MenuActivateSkullIconButton[];
extern char MenuDeactivateButton[];
extern char MenuDeactivateLevelSelectButton[];
extern char MenuDeactivateSkullIconButton[];
extern char Menu_CycleOptionAndPlaySound[];
extern char Menu_DecrementAndPlaySound[];
extern char Menu_DecrementCounter[];
extern char Menu_IncrementSelection[];
extern char Menu_PlayConfirmSound[];
extern char Menu_PlayConfirmSoundIfEnabled[];
extern char Menu_PlaySelectSoundIfEnabled[];
extern char OptionsMenuDestroyCallback[];
extern char PasswordBackspaceHandler[];
extern char PasswordDigitInputHandler[];
extern char PasswordDigitSelectActive[];
extern char PasswordDigitSelectInactive[];
extern char PasswordSubmitEventHandler[];
extern char RunnDestroyCallback_Simple[];
extern char RunnDestroyCallback_Vtable0x80011d54[];
extern char RunnDestroyCallback_Vtable0x80011d74[];
extern char UpdateEntityRender[];
extern char UploadEntityTextureIfDirty[];
extern char func_80075B7C[];
extern char func_80075F24[];

void *D_80011D54[8] = {
    0,
    0,
    0,
    (void *)RunnDestroyCallback_Vtable0x80011d54,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011D74[8] = {
    0,
    0,
    0,
    (void *)RunnDestroyCallback_Vtable0x80011d74,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011D94[8] = {
    0,
    0,
    0,
    (void *)RunnDestroyCallback_Simple,
    0,
    (void *)unresolved_800732cc  /* UNRESOLVED 0x800732cc */,
    0,
    (void *)unresolved_800732c4  /* UNRESOLVED 0x800732c4 */
};

void *D_80011DB4[8] = {
    0,
    0,
    0,
    (void *)EntityDestructor_WithSPUStopAndFree,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011DD4[7] = {
    0,
    0,
    0,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011DF4[8] = {
    0,
    0,
    0,
    (void *)FinnDestroyCallback_Simple,
    0,
    (void *)unresolved_80074094  /* UNRESOLVED 0x80074094 */,
    0,
    (void *)unresolved_8007408c  /* UNRESOLVED 0x8007408c */
};

void *D_80011E14[8] = {
    0,
    0,
    0,
    (void *)FinnDestroyWithSoundCleanup,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011E34[8] = {
    0,
    0,
    0,
    (void *)FinnDestroyCallback_Vtable0x80011e34,
    0,
    (void *)unresolved_80074f2c  /* UNRESOLVED 0x80074f2c */,
    0,
    (void *)unresolved_80074f24  /* UNRESOLVED 0x80074f24 */
};

void *D_80011E54[8] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_1E54,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011E74[8] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_1E74,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011E94[8] = {
    0,
    0,
    0,
    (void *)OptionsMenuDestroyCallback,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011EB4[8] = {
    0,
    0,
    0,
    (void *)unresolved_80079d88  /* UNRESOLVED 0x80079d88 */,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_80011ED4[22] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_2034,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    (void *)PasswordDigitSelectActive,
    0,
    (void *)PasswordDigitSelectInactive,
    0,
    (void *)PasswordSubmitEventHandler,
    0,
    (void *)EndingNoopCallback_80079dec,
    0,
    (void *)EndingNoopCallback_80079fa0,
    0,
    (void *)PasswordBackspaceHandler,
    0,
    (void *)PasswordDigitInputHandler
};

void *D_80011F2C[22] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_2034_V2,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    (void *)MenuActivateSkullIconButton,
    0,
    (void *)MenuDeactivateSkullIconButton,
    0,
    (void *)func_80075F24,
    0,
    (void *)Menu_PlayConfirmSound,
    0,
    (void *)Menu_CycleOptionAndPlaySound,
    0,
    (void *)Menu_DecrementCounter,
    0,
    (void *)EndingNoopCallback_80079f90
};

void *D_80011F84[22] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_2034_V3,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    (void *)MenuActivateLevelSelectButton,
    0,
    (void *)MenuDeactivateLevelSelectButton,
    0,
    (void *)func_80075B7C,
    0,
    (void *)Menu_PlayConfirmSound,
    0,
    (void *)Menu_IncrementSelection,
    0,
    (void *)Menu_DecrementAndPlaySound,
    0,
    (void *)EndingNoopCallback_80079f90
};

void *D_80011FDC[22] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_2034_V4,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    (void *)MenuActivateButtonWithReset,
    0,
    (void *)FINN_ClearSubentityState,
    0,
    (void *)Menu_PlaySelectSoundIfEnabled,
    0,
    (void *)Menu_PlayConfirmSoundIfEnabled,
    0,
    (void *)EndingNoopCallback_80079fa0,
    0,
    (void *)EndingNoopCallback_80079f98,
    0,
    (void *)EndingNoopCallback_80079f90
};

void *D_80012034[22] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_2034_V5,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty,
    0,
    (void *)MenuActivateButton,
    0,
    (void *)MenuDeactivateButton,
    0,
    (void *)EndingNoopCallback_80079fa8,
    0,
    (void *)Menu_PlayConfirmSound,
    0,
    (void *)EndingNoopCallback_80079fa0,
    0,
    (void *)EndingNoopCallback_80079f98,
    0,
    (void *)EndingNoopCallback_80079f90
};

void *D_8001208C[8] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_208C,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800120AC[8] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_20AC,
    0,
    (void *)UpdateEntityRender,
    0,
    (void *)UploadEntityTextureIfDirty
};

void *D_800120CC[8] = {
    0,
    0,
    0,
    (void *)EndingEntityDestroyCallback_20CC,
    0,
    (void *)EndingNoopCallback_8007a0e4,
    0,
    (void *)EndingNoopCallback_8007a0dc
};
