/**
 * config.js - Sprite ID mappings extracted from game binaries
 * 
 * Generated by scripts/extract_sprite_ids.py
 * Sources: PAL and JP
 * 
 * These sprite IDs are hardcoded in the game code and passed to
 * the sprite setup function. Each entity type has a specific sprite ID
 * that maps to sprites in the BLB file.
 * 
 * Sprite IDs are IDENTICAL between PAL and JP versions - only the
 * code addresses differ (see docs/pal-jp-comparison.md).
 */

// Region-specific addresses for sprite setup function
const REGION_ADDRESSES = {
    PAL: {
        spriteSetupFunc: 0x8001d080,  // FUN_8001d080
        initEntitySprite: 0x8001c720,
        gameState: 0x800ae3e8,
    },
    JP: {
        spriteSetupFunc: 0x8001d484,  // FUN_8001d484 (+0x404)
        initEntitySprite: 0x8001cb24,
        gameState: 0x800af34c,
    }
};

// All sprite IDs found in binaries (138 unique IDs)
const SPRITE_IDS = {
    0x0005c699: { id: 378521, regions: 'BOTH' },
    0x000cc8f8: { id: 837880, regions: 'BOTH' },
    0x00388110: { id: 3703056, regions: 'BOTH' },
    0x006b9a6f: { id: 7051887, regions: 'BOTH' },
    0x022e3442: { id: 36582466, regions: 'BOTH' },
    0x02ed1470: { id: 49091696, regions: 'BOTH' },
    0x0305a4f5: { id: 50701557, regions: 'BOTH' },
    0x04084011: { id: 67649553, regions: 'BOTH' },
    0x04835000: { id: 75714560, regions: 'BOTH' },
    0x052aa082: { id: 86679682, regions: 'BOTH' },
    0x0628a800: { id: 103327744, regions: 'BOTH' },
    0x0708a4a0: { id: 118006944, regions: 'BOTH' },
    0x08192250: { id: 135864912, regions: 'BOTH' },
    0x085860d4: { id: 140009684, regions: 'BOTH' },
    0x088c5011: { id: 143413265, regions: 'BOTH' },
    0x08bc8013: { id: 146571283, regions: 'BOTH' },
    0x092b8480: { id: 153846912, regions: 'BOTH' },
    0x093080c8: { id: 154173640, regions: 'BOTH' },
    0x09382152: { id: 154673490, regions: 'BOTH' },
    0x09406d8a: { id: 155217290, regions: 'BOTH' },
    0x09993072: { id: 161034354, regions: 'BOTH' },
    0x0a08c490: { id: 168346768, regions: 'BOTH' },
    0x0a3a4051: { id: 171589713, regions: 'BOTH' },
    0x0aabc010: { id: 179027984, regions: 'BOTH' },
    0x0ad0f813: { id: 181467155, regions: 'BOTH' },
    0x0b0811bb: { id: 185078203, regions: 'BOTH' },
    0x0b081dbb: { id: 185081275, regions: 'BOTH' },
    0x0b2084d0: { id: 186680528, regions: 'BOTH' },
    0x0b290ba2: { id: 187239330, regions: 'BOTH' },
    0x0bbb70ac: { id: 196833452, regions: 'BOTH' },
    0x0c01c014: { id: 201441300, regions: 'BOTH' },
    0x0e0ac230: { id: 235586096, regions: 'BOTH' },
    0x0e3889be: { id: 238586302, regions: 'BOTH' },
    0x10057441: { id: 268792897, regions: 'BOTH' },
    0x18298210: { id: 405373456, regions: 'BOTH' },
    0x193ca112: { id: 423403794, regions: 'BOTH' },
    0x1a202d81: { id: 438316417, regions: 'BOTH' },
    0x1a28c11a: { id: 438878490, regions: 'BOTH' },
    0x1a2c8516: { id: 439125270, regions: 'BOTH' },
    0x1a3109b2: { id: 439421362, regions: 'BOTH' },
    0x1b280858: { id: 455608408, regions: 'BOTH' },
    0x1b280c33: { id: 455609395, regions: 'BOTH' },
    0x1b301085: { id: 456134789, regions: 'BOTH' },
    0x1c3aa013: { id: 473604115, regions: 'BOTH' },
    0x1c8c2437: { id: 478946359, regions: 'BOTH' },
    0x1d1811b3: { id: 488116659, regions: 'BOTH' },
    0x1e089010: { id: 503877648, regions: 'BOTH' },
    0x1e1000b3: { id: 504365235, regions: 'BOTH' },
    0x1e181d10: { id: 504896784, regions: 'BOTH' },
    0x1e28e0d4: { id: 505995476, regions: 'JP' },
    0x20211e5f: { id: 539041375, regions: 'BOTH' },
    0x21229c5c: { id: 555916380, regions: 'BOTH' },
    0x212a9c2d: { id: 556440621, regions: 'BOTH' },
    0x21842018: { id: 562307096, regions: 'BOTH' },
    0x21a81d54: { id: 564665684, regions: 'BOTH' },
    0x282b8491: { id: 673940625, regions: 'BOTH' },
    0x292e8480: { id: 690914432, regions: 'BOTH' },
    0x2b79835d: { id: 729383773, regions: 'BOTH' },
    0x2c182010: { id: 739778576, regions: 'BOTH' },
    0x2d688254: { id: 761823828, regions: 'BOTH' },
    0x323ac9be: { id: 842713534, regions: 'BOTH' },
    0x34014841: { id: 872499265, regions: 'BOTH' },
    0x35289fae: { id: 891854766, regions: 'BOTH' },
    0x3838801a: { id: 943226906, regions: 'BOTH' },
    0x392cb014: { id: 959229972, regions: 'BOTH' },
    0x393c80c2: { id: 960266434, regions: 'BOTH' },
    0x39900619: { id: 965740057, regions: 'BOTH' },
    0x3a3a49b2: { id: 976898482, regions: 'BOTH' },
    0x3c389550: { id: 1010341200, regions: 'BOTH' },
    0x40098a60: { id: 1074367072, regions: 'BOTH' },
    0x40106054: { id: 1074815060, regions: 'BOTH' },
    0x407801d0: { id: 1081606608, regions: 'BOTH' },
    0x407801dc: { id: 1081606620, regions: 'BOTH' },
    0x410800f9: { id: 1091043577, regions: 'BOTH' },
    0x410808f9: { id: 1091045625, regions: 'BOTH' },
    0x410818f9: { id: 1091049721, regions: 'BOTH' },
    0x424d1840: { id: 1112348736, regions: 'BOTH' },
    0x458b0320: { id: 1166738208, regions: 'BOTH' },
    0x48204012: { id: 1210073106, regions: 'BOTH' },
    0x4a298690: { id: 1244235408, regions: 'BOTH' },
    0x4c106054: { id: 1276141652, regions: 'BOTH' },
    0x4d09d01c: { id: 1292488732, regions: 'BOTH' },
    0x5238cd10: { id: 1379454224, regions: 'BOTH' },
    0x53209c1c: { id: 1394646044, regions: 'BOTH' },
    0x5900c41e: { id: 1493222430, regions: 'BOTH' },
    0x5a088840: { id: 1510508608, regions: 'BOTH' },
    0x5a2082f2: { id: 1512080114, regions: 'BOTH' },
    0x60181a0c: { id: 1612192268, regions: 'BOTH' },
    0x60a91c9c: { id: 1621695644, regions: 'BOTH' },
    0x60aa1c9c: { id: 1621761180, regions: 'BOTH' },
    0x60b8bc9c: { id: 1622719644, regions: 'BOTH' },
    0x60b93cbd: { id: 1622752445, regions: 'BOTH' },
    0x60b98cbd: { id: 1622772925, regions: 'BOTH' },
    0x60de1050: { id: 1625165904, regions: 'BOTH' },
    0x611c5804: { id: 1629247492, regions: 'BOTH' },
    0x63848e59: { id: 1669631577, regions: 'BOTH' },
    0x64bb1cbe: { id: 1689984190, regions: 'BOTH' },
    0x657c322c: { id: 1702638124, regions: 'BOTH' },
    0x69588258: { id: 1767408216, regions: 'BOTH' },
    0x69c8f473: { id: 1774777459, regions: 'BOTH' },
    0x6c22083a: { id: 1814169658, regions: 'BOTH' },
    0x6c289c1c: { id: 1814600732, regions: 'BOTH' },
    0x6d209c95: { id: 1830853781, regions: 'BOTH' },
    0x70a09ce1: { id: 1889574113, regions: 'BOTH' },
    0x8068815c: { id: 2154332508, regions: 'BOTH' },
    0x80e85ea0: { id: 2162712224, regions: 'BOTH' },
    0x8139e009: { id: 2168053769, regions: 'PAL' },
    0x8524a880: { id: 2233772160, regions: 'BOTH' },
    0x8569a090: { id: 2238292112, regions: 'BOTH' },
    0x880161a7: { id: 2281791911, regions: 'BOTH' },
    0x88210498: { id: 2283865240, regions: 'BOTH' },
    0x883d14b4: { id: 2285704372, regions: 'BOTH' },
    0x88b9833c: { id: 2293859132, regions: 'BOTH' },
    0x8a3809f2: { id: 2318928370, regions: 'BOTH' },
    0x8a7ce022: { id: 2323439650, regions: 'BOTH' },
    0x8b7ce0b2: { id: 2340217010, regions: 'BOTH' },
    0x8c29e08c: { id: 2351554700, regions: 'BOTH' },
    0x8d01c734: { id: 2365703988, regions: 'BOTH' },
    0x91106183: { id: 2433769859, regions: 'BOTH' },
    0x9158a0f6: { id: 2438504694, regions: 'BOTH' },
    0x980861a3: { id: 2550686115, regions: 'BOTH' },
    0x9918a8e2: { id: 2568530146, regions: 'BOTH' },
    0x9b0ab1c6: { id: 2601169350, regions: 'BOTH' },
    0x9c6584d2: { id: 2623898834, regions: 'BOTH' },
    0xa0299a4d: { id: 2687081037, regions: 'BOTH' },
    0xa116220c: { id: 2702582284, regions: 'BOTH' },
    0xa9226042: { id: 2837602370, regions: 'BOTH' },
    0xb4011101: { id: 3019968769, regions: 'BOTH' },
    0xbb781481: { id: 3145208961, regions: 'BOTH' },
    0xc87ca082: { id: 3363610754, regions: 'BOTH' },
    0xc8f90114: { id: 3371761940, regions: 'BOTH' },
    0xd02dc3d5: { id: 3492660181, regions: 'BOTH' },
    0xe4834384: { id: 3833807748, regions: 'BOTH' },
    0xe4cb8330: { id: 3838542640, regions: 'BOTH' },
    0xe6830101: { id: 3867345153, regions: 'BOTH' },
    0xe7443a6f: { id: 3880008303, regions: 'BOTH' },
    0xed209c94: { id: 3978337428, regions: 'BOTH' },
    0xf175320e: { id: 4050989582, regions: 'BOTH' },
};

// Entity type number → sprite ID mapping (used by engine.js for rendering)
// These are the numeric entity types from Asset 501 entity data
// See docs/entity-system.md for full entity documentation
const ENTITY_SPRITE_MAP = {
    // Type 2: Clayball collectible
    2: 0x09406d8a,
    
    // Type 8: Item/collectible (flying object)
    8: 0x0c34aa22,
    
    // Type 25: Enemy type 1
    25: 0x1e1000b3,
    
    // Type 27: Enemy type 2
    27: 0x182d840c,
    
    // Type 42: Portal/warp point
    42: 0xb01c25f0,
    
    // Type 45: Message/save box
    45: 0xa89d0ad0,
    
    // Type 50: Boss main entity
    50: 0x181c3854,
    
    // Type 51: Boss sub-entity/part
    51: 0x8818a018,
    
    // Type 60: Particle effect
    60: 0x168254b5,
    
    // Type 61: Sparkle effect
    61: 0x6a351094,
};

// Named entity lookup (for UI/debugging)
const KNOWN_ENTITIES = {
    // Player
    'player': { spriteId: 0x21842018, name: 'Klaymen (Player)' },
    
    // Boss entities
    'boss_main': { spriteId: 0x181c3854, name: 'Boss Main Body' },
    'boss_part': { spriteId: 0x8818a018, name: 'Boss Sub-Part' },
    'boss_detail': { spriteId: 0x0244655d, name: 'Boss Detail' },
    
    // Menu/UI
    'menu_frame': { spriteId: 0xb8700ca1, name: 'Menu Frame' },
    'menu_text': { spriteId: 0x00e2f188, name: 'Menu Text' },
    'button': { spriteId: 0xa9240484, name: 'Button' },
    'icon': { spriteId: 0x88a28194, name: 'Icon' },
    
    // Collectibles
    'clayball': { spriteId: 0x09406d8a, name: 'Clay Ball' },
};

// Sprite ID to friendly name lookup
const SPRITE_NAMES = {};
for (const [key, val] of Object.entries(KNOWN_ENTITIES)) {
    const hexId = '0x' + val.spriteId.toString(16).padStart(8, '0');
    SPRITE_NAMES[hexId] = val.name;
}

// Export for use in other modules
if (typeof window !== 'undefined') {
    window.SpriteConfig = { 
        REGION_ADDRESSES, 
        SPRITE_IDS, 
        ENTITY_SPRITE_MAP,
        KNOWN_ENTITIES, 
        SPRITE_NAMES 
    };
}

// For Node.js/CommonJS
if (typeof module !== 'undefined') {
    module.exports = { REGION_ADDRESSES, SPRITE_IDS, ENTITY_SPRITE_MAP, KNOWN_ENTITIES, SPRITE_NAMES };
}
