name: SLES_010.90
sha1: 5a14b65cb44813bfed1ee53c6a3f4456bc230f97
options:
  basename: game
  target_path: disks/pal/SLES_010.90
  elf_path: build/pal/game.elf
  base_path: ..
  platform: psx
  compiler: PSYQ

  asm_path: asm/pal
  src_path: src
  build_path: build/pal
  # create_asm_dependencies: True

  ld_script_path: build/pal/game.ld
  ld_dependencies: True

  find_file_boundaries: True
  gp_value: 0x800A5954
  # ld_gp_expression: main_SCOMMON_START + 0x7FF0

  o_as_suffix: True
  use_legacy_include_asm: False

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt

  # undefined_funcs_auto_path: undefined_funcs_auto.txt
  # undefined_syms_auto_path: undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  subalign: 2

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  # Uncomment this line if you need to use the maspsx reorder workaround hack
  # https://github.com/mkst/maspsx?tab=readme-ov-file#include_asm-reordering-workaround-hack
  # include_asm_macro_style: maspsx_hack
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    bss_size: 0x82C0  # .sbss (0x48) + .bss (0x8278)
    subsegments:
      # .rdata section: 0x80010000 - 0x800131EF
      - [0x800, rodata]
      # .text section: 0x800131F0 - 0x800907EB (includes .text.split)
      - [0x39F0, asm]
      # .data section: 0x800907EC - 0x800A5953
      - [0x80FEC, data]
      # .sdata section: 0x800A5954 - 0x800A611F
      - [0x96154, data, sdata]
      # .sbss: 0x800A6120 - 0x800A6167 (handled by bss_size)
      # .bss:  0x800A6168 - 0x800AE3DF (handled by bss_size)
  - [0x9691F]  # End of .sdata in file
