// Set return types for functions whose return was placeholder undefinedN, using
// evidence-based, size-faithful rules (see /tmp/ret_types.tsv, generated by
// tools offline): undefined1->uchar, undefined2->ushort, and undefined4 that
// returns only 0/1/literals -> int. Run via plain-install analyzeHeadless.
// Idempotent. Reads /tmp/ret_types.tsv (name<TAB>type).
//@category Skullmonkeys
import ghidra.app.script.GhidraScript;
import ghidra.program.model.data.*;
import ghidra.program.model.listing.Function;
import ghidra.program.model.symbol.SourceType;
import java.nio.file.*;
import java.util.List;

public class SetReturnTypes extends GhidraScript {

    @Override
    public void run() throws Exception {
        int tx = currentProgram.startTransaction("audit: set undefinedN return types");
        boolean ok = false;
        int done = 0, miss = 0;
        try {
            for (String line : Files.readAllLines(Paths.get("/tmp/ret_types.tsv"))) {
                if (line.isBlank()) continue;
                String[] p = line.split("\t");
                String name = p[0].trim(), tn = p[1].trim();
                DataType dt = tn.equals("uchar") ? UnsignedCharDataType.dataType
                            : tn.equals("ushort") ? UnsignedShortDataType.dataType
                            : IntegerDataType.dataType;
                List<Function> fns = getGlobalFunctions(name);
                if (fns.isEmpty()) { println("!! no function: " + name); miss++; continue; }
                for (Function f : fns) {
                    String old = f.getReturnType().getName();
                    if (old.equals(tn)) continue;
                    f.setReturnType(dt, SourceType.USER_DEFINED);
                    println("RET " + name + ": " + old + " -> " + tn);
                    done++;
                }
            }
            ok = true;
        } finally {
            currentProgram.endTransaction(tx, ok);
        }
        println("SetReturnTypes done: " + done + " set, " + miss + " missing (committed=" + ok + ")");
    }
}
