/* =============================================================================
 * PlayerCallback_FallingPhysicsMain.c  --  PC-port airborne physics core
 * =============================================================================
 * Functional-C conversion of PlayerCallback_FallingPhysicsMain (0x800650C4,
 * 0x18CC -- the largest playst function: horizontal momentum + cushion,
 * gravity, multi-height ceiling/wall probes, bounce/platform/death tile
 * handling, and the falling-input state transitions).
 *
 * PROVENANCE: generated by m2c from asm/nonmatchings/playst/PlayerCallback_
 * FallingPhysicsMain.s with a typed PlayerEntity context, then mechanically
 * cleaned: saved_reg_* artifacts zeroed (dead on the direct-dispatch path,
 * same unaff_s2 pattern as every FSM dispatch), unk field accesses rewritten
 * as byte-offset macros, slot-table reads as S32AT(slot,-8/-4). Ghidra splits
 * this region into ~10 pseudo-functions; the project (and this file) keep it
 * as the single real function.
 * ========================================================================== */
#include "common.h"
#include "globals.h"
#include "Game/entity.h"
#include "Game/game_state.h"
#include <stdint.h>

#define U8AT(p, off)  (*(u8 *)((u8 *)(p) + (off)))
#define S16AT(p, off) (*(s16 *)((u8 *)(p) + (off)))
#define S32AT(p, off) (*(s32 *)((u8 *)(p) + (off)))

extern u8  EntityApplyMovementCallbacks(void *e, s16 x, s16 y);
extern s16 TransformXCoordWithScaleSnapped(void *e, s16 x);
extern s16 TransformYCoordWithScaleSnapped(void *e, s16 y);
extern s16 PlayerApplyPositionWithCollision(void *e, u8 a1, s16 x, s16 y);
extern void PlayerProcessBounceCollision(void *e, u8 tile);
extern s32 IsEntityNearSoundTrigger(void *e, u8 a1, s16 x, s16 y, s32 a4);
extern void SpawnPlayerDeathEffect(void *e, s32 a1);
extern void EntitySetState(void *e, u32 marker, u32 fn);
extern void PlayEntityPositionSound(void *e, u32 id);
extern void GetEntityScreenBounds(void *e, s16 *out);
extern void *CheckEntityPointCollisionWithOffsets(void *gs, s32 a1, s32 a2, s32 a3);
extern void *CheckPointCollisionAndNotify(void *gs, s32 a1, s16 a2, s32 a3, s32 a4, s32 a5, void *a6);

extern u16 D_800A596C asm("D_800A596C");
extern u32 D_800A5D30 asm("D_800A5D30");
extern u32 D_800A5D34 asm("D_800A5D34");
extern u32 D_800A5D78 asm("D_800A5D78");
extern u32 D_800A5D7C asm("D_800A5D7C");
extern u32 D_800A5D98 asm("D_800A5D98");
extern u32 D_800A5D9C asm("D_800A5D9C");
extern u32 D_800A5E00 asm("D_800A5E00");
extern u32 D_800A5E04 asm("D_800A5E04");
extern u32 D_800A5E08 asm("D_800A5E08");
extern u32 D_800A5E0C asm("D_800A5E0C");
extern u32 D_800A5E58 asm("D_800A5E58");
extern u32 D_800A5E5C asm("D_800A5E5C");
extern u32 D_800A5ED4 asm("D_800A5ED4");
extern u32 D_800A5ED8 asm("D_800A5ED8");
extern u32 D_800A5EDC asm("D_800A5EDC");
extern u32 D_800A5EE0 asm("D_800A5EE0");
extern u32 D_800A5EE4 asm("D_800A5EE4");
extern u32 D_800A5EE8 asm("D_800A5EE8");
extern u32 D_800A5EEC asm("D_800A5EEC");
extern u32 D_800A5EF0 asm("D_800A5EF0");
extern u16 D_800A596C_j asm("D_800A596C");

void PlayerCallback_FallingPhysicsMain(PlayerEntity *e) {
    u8 sp20;
    u8 sp21;
    u8 sp22;
    u8 sp23;
    u8 sp24;
    u8 sp25;
    s16 sp28;
    s16 sp2A;
    s16 sp2C;
    s16 sp2E;
    s32 sp48;
    s16 (*sp4C)(u8 *, s16);
    s32 sp60;
    s16 (*sp64)(u8 *, s16);
    s32 sp70;
    s16 (*sp74)(u8 *, s16);
    s32 sp80;
    s16 (*sp84)(u8 *, s16);
    s32 sp90;
    s16 (*sp94)(u8 *, s16);
    s32 spA0;
    s16 (*spA4)(u8 *, s16);
    s32 spB8;
    void (*spBC)(Entity *);
    s32 spC8;
    s16 (*spCC)(u8 *, s16);
    s32 spD8;
    s16 (*spDC)(u8 *, s16);
    Entity *temp_a0_19;
    Entity *temp_a0_20;
    Entity *var_s1_3;
    s16 (*var_a2)(u8 *, s16);
    s16 (*var_a2_11)(u8 *, s16);
    s16 (*var_a2_12)(u8 *, s16);
    s16 (*var_a2_2)(u8 *, s16);
    s16 (*var_a2_3)(u8 *, s16);
    s16 (*var_a2_6)(u8 *, s16);
    s16 (*var_a2_8)(u8 *, s16);
    s16 (*var_a2_9)(u8 *, s16);
    s16 (*var_a3_4)(u8 *, s16);
    s16 temp_a0_11;
    s16 temp_a0_14;
    s16 temp_a0_15;
    s16 temp_a0_16;
    s16 temp_a0_17;
    s16 temp_a0_18;
    s16 temp_a0_6;
    s16 temp_a0_8;
    s16 temp_a0_9;
    s16 temp_a1_3;
    s16 temp_a2;
    s16 temp_a2_2;
    s16 temp_a3;
    s16 temp_a3_2;
    s16 temp_v1_10;
    s16 temp_v1_11;
    s16 temp_v1_12;
    s16 temp_v1_13;
    s16 temp_v1_15;
    s16 temp_v1_16;
    s16 temp_v1_17;
    s16 temp_v1_2;
    s16 temp_v1_5;
    s16 temp_v1_6;
    s16 temp_v1_7;
    s16 temp_v1_8;
    s16 temp_v1_9;
    s16 var_a1_9;
    s16 var_a2_7;
    s32 var_a3;   /* X position accumulator -- FULL 32-bit register ($a3) in the
                   * .s: sra v0,a3,16 -> worldX; sh a3,0x6C keeps the subpixel
                   * half. m2c's s16 type truncated (worldX<<16) to 0 (the
                   * player-teleports-to-origin bug). */
    s16 var_a3_2;
    s16 var_a3_3;
    s32 var_s1;   /* Y position accumulator -- same full-register pattern ($s1) */
    s16 var_v0_10;
    s16 var_v0_11;
    s16 var_v0_14;
    s16 var_v0_18;
    s16 var_v0_20;
    s16 var_v0_22;
    s16 var_v0_23;
    s16 var_v0_25;
    s16 var_v0_26;
    s16 var_v0_29;
    s16 var_v0_30;
    s16 var_v0_31;
    s16 var_v0_6;
    s16 var_v0_8;
    s16 var_v1_3;
    s16 var_v1_4;
    s16 var_v1_5;
    s32 temp_a0;
    s32 temp_a0_10;
    s32 temp_a0_12;
    s32 temp_a0_13;
    s32 temp_a0_2;
    s32 temp_a0_3;
    s32 temp_a0_4;
    s32 temp_a0_5;
    s32 temp_a0_7;
    s32 temp_lo;
    s32 temp_lo_2;
    s32 temp_lo_3;
    s32 temp_s1;
    s32 temp_s1_2;
    s32 temp_s1_5;
    s32 temp_v0;
    s32 temp_v0_10;
    s32 temp_v0_2;
    s32 temp_v0_7;
    s32 temp_v0_9;
    s32 temp_v1;
    s32 temp_v1_14;
    s32 temp_v1_3;
    s32 temp_v1_4;
    s32 var_a0;
    s32 var_a0_2;
    s32 var_a0_3;
    s32 var_a2_10;
    s32 var_s1_2;
    s32 var_s1_4;
    s32 var_s2;
    s32 var_s2_2;
    s32 var_s2_3;
    s32 var_s2_4;
    s32 var_s2_5;
    s32 var_s3;
    s32 var_s3_2;
    s32 var_s4;
    s32 var_s6;
    s32 var_v0;
    s32 var_v0_12;
    s32 var_v0_13;
    s32 var_v0_15;
    s32 var_v0_16;
    s32 var_v0_17;
    s32 var_v0_19;
    s32 var_v0_21;
    s32 var_v0_24;
    s32 var_v0_27;
    s32 var_v0_28;
    s32 var_v0_2;
    s32 var_v0_32;
    s32 var_v0_33;
    s32 var_v0_34;
    s32 var_v0_3;
    s32 var_v0_4;
    s32 var_v0_5;
    s32 var_v0_7;
    s32 var_v0_9;
    s32 var_v1;
    s32 var_v1_2;
    s32 var_v1_6;
    u16 temp_a1_2;
    u16 temp_a1_4;
    u16 temp_a1_5;
    u16 temp_v0_18;
    u16 temp_v0_21;
    u16 temp_v1_20;
    u16 var_a1_2;
    u16 var_a1_6;
    u32 temp_s0_2;
    u32 temp_v1_18;
    u32 temp_v1_19;
    u32 var_a1_4;
    u32 var_a1_5;
    u32 var_a2_4;
    u32 var_a2_5;
    u32 var_v1_7;
    u8 temp_a1;
    u8 temp_a1_6;
    u8 temp_s0;
    u8 temp_s1_3;
    u8 temp_s1_4;
    u8 temp_s2;
    u8 temp_v0_11;
    u8 temp_v0_14;
    u8 temp_v0_15;
    u8 temp_v0_17;
    u8 temp_v0_19;
    u8 temp_v0_20;
    u8 temp_v0_22;
    u8 temp_v0_23;
    u8 temp_v0_25;
    u8 temp_v0_26;
    u8 temp_v0_3;
    u8 temp_v0_4;
    u8 temp_v0_5;
    u8 temp_v0_6;
    u8 var_a1;
    u8 var_a1_3;
    u8 var_a1_7;
    u8 var_a1_8;
    void (*var_t0)(Entity *);
    void *temp_v0_12;
    void *temp_v0_13;
    void *temp_v0_16;
    void *temp_v0_24;
    void *temp_v0_27;
    void *temp_v0_28;
    void *temp_v0_29;
    void *temp_v0_30;
    void *temp_v0_31;
    void *temp_v0_32;
    void *temp_v0_8;

    var_s2 = 0;   /* dead on direct-dispatch path */
    var_s6 = 0;   /* dead on direct-dispatch path */
    var_s4 = 0;
    temp_s1 = (e->sprite.base.worldY << 0x10) + (u16) e->sprite.base.velocityY;
    temp_a0 = e->carryMotionX;
    if (temp_a0 > 0) {
        temp_v0 = temp_a0 - 0x4000;
        e->carryMotionX = temp_v0;
        if (temp_v0 < 0) {
            e->carryMotionX = 0;
        }
    } else {
        temp_v0_2 = temp_a0 + 0x4000;
        if (temp_a0 < 0) {
            e->carryMotionX = temp_v0_2;
            if (temp_v0_2 > 0) {
                e->carryMotionX = 0;
            }
        }
    }
    temp_v1 = e->velocityX_fixed;
    if (temp_v1 > 0) {
        var_v0 = e->carryMotionX < temp_v1;
        goto block_10;
    }
    if (temp_v1 < 0) {
        var_v0 = temp_v1 < e->carryMotionX;
block_10:
        if (var_v0 != 0) {
            e->carryMotionX = temp_v1;
        }
    }
    e->velocityX_fixed = 0;
    var_a3 = (e->sprite.base.worldX << 0x10) + (u16) e->sprite.base.velocityX + e->carryMotionX;
    if (e->groundedFlag != 0) {
        var_a3 += e->pushX << 0x10;
    }
    e->sprite.base.worldX = (s16) (var_a3 >> 0x10);
    e->sprite.base.velocityX = var_a3;
    temp_v0_3 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, e->sprite.base.worldY);
    sp20 = temp_v0_3;
    if (((u32) ((temp_v0_3 + 0x4B) & 0xFF) < 3U) || (temp_a0_2 = temp_v0_3 & 0xFF, (temp_a0_2 == 0xC9)) || (temp_a0_2 == 0xCB) || (var_v0_2 = 0, (((u32) ((temp_v0_3 + 0x23) & 0xFF) < 3U) != 0))) {
        if (e->invincibilityTimer != 0) {
            sp20 = 0x65;
            var_v0_2 = 0;
        } else {
            var_v0_2 = 1;
        }
    }
    if (var_v0_2 & 0xFF) {
        var_a1 = sp20;
        goto block_54;
    }
    temp_v0_4 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) ((u16) e->sprite.base.worldY - 0x10));
    sp21 = temp_v0_4;
    if (((u32) ((temp_v0_4 + 0x4B) & 0xFF) < 3U) || (temp_a0_3 = temp_v0_4 & 0xFF, (temp_a0_3 == 0xC9)) || (temp_a0_3 == 0xCB) || (var_v0_3 = 0, (((u32) ((temp_v0_4 + 0x23) & 0xFF) < 3U) != 0))) {
        if (e->invincibilityTimer != 0) {
            sp21 = 0x65;
            var_v0_3 = 0;
        } else {
            var_v0_3 = 1;
        }
    }
    if (var_v0_3 & 0xFF) {
        var_a1 = sp21;
        goto block_54;
    }
    temp_v0_5 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) ((u16) e->sprite.base.worldY - 0x20));
    sp22 = temp_v0_5;
    if (((u32) ((temp_v0_5 + 0x4B) & 0xFF) < 3U) || (temp_a0_4 = temp_v0_5 & 0xFF, (temp_a0_4 == 0xC9)) || (temp_a0_4 == 0xCB) || (var_v0_4 = 0, (((u32) ((temp_v0_5 + 0x23) & 0xFF) < 3U) != 0))) {
        if (e->invincibilityTimer != 0) {
            sp22 = 0x65;
            var_v0_4 = 0;
        } else {
            var_v0_4 = 1;
        }
    }
    if (var_v0_4 & 0xFF) {
        var_a1 = sp22;
        goto block_54;
    }
    temp_v0_6 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) ((u16) e->sprite.base.worldY - 0x30));
    sp23 = temp_v0_6;
    if (((u32) ((temp_v0_6 + 0x4B) & 0xFF) < 3U) || (temp_a0_5 = temp_v0_6 & 0xFF, (temp_a0_5 == 0xC9)) || (temp_a0_5 == 0xCB) || (var_v0_5 = 0, (((u32) ((temp_v0_6 + 0x23) & 0xFF) < 3U) != 0))) {
        if (e->invincibilityTimer != 0) {
            sp23 = 0x65;
            var_v0_5 = 0;
        } else {
            var_v0_5 = 1;
        }
    }
    if (var_v0_5 & 0xFF) {
        var_a1 = sp23;
block_54:
        PlayerProcessBounceCollision(e, var_a1);
        return;
    }
    if ((sp20 == 0x65) || (sp21 == 0x65) || (sp22 == 0x65) || (sp23 == 0x65)) {
        temp_v0_7 = e->carryMotionX;
        if (temp_v0_7 > 0) {
            temp_a0_6 = S16AT(e, 0x26);
            var_a1_2 = (u16) e->sprite.base.worldX;
            e->carryMotionX = 0;
            if (temp_a0_6 != 0) {
                if (temp_a0_6 > 0) {
                    temp_v0_8 = (temp_a0_6 * 8) + S32AT(e, S16AT(e, 0x28));
                    var_s2 = S32AT(temp_v0_8, -8);
                    var_a2 = S32AT(temp_v0_8, -4);
                } else {
                    var_a2 = e->sprite.base.moveCallbackX;
                }
                temp_v1_2 = S16AT(e, 0x24);
                if ((temp_a0_6 << 0x10) > 0) {
                    var_v0_6 = (s16) var_s2 + temp_v1_2;
                } else {
                    var_v0_6 = temp_v1_2;
                }
                var_a1_2 = var_a2(e + var_v0_6, (s16) var_a1_2);
            }
            e->sprite.base.velocityX = 0;
            e->sprite.base.worldX = (s16) ((s32) ((var_a1_2 & ~0xF) << 0x10) / (s32) e->sprite.base.scalePowerupX) - 1;
        } else if (temp_v0_7 < 0) {
            e->carryMotionX = 0;
            e->sprite.base.worldX = TransformXCoordWithScaleSnapped(e, e->sprite.base.worldX);
            e->sprite.base.velocityX = 0;
        }
    }
    temp_v1_3 = e->cushionVelY;
    if (temp_v1_3 != 0) {
        e->cushionVelY = 0;
        temp_v0_9 = e->velocityY_fixed + temp_v1_3;
        var_s1 = temp_s1 + temp_v0_9;
        e->velocityY_fixed = temp_v0_9;
    } else if (e->groundedFlag == 0) {
        temp_v0_10 = e->velocityY_fixed + 0x5000;
        e->velocityY_fixed = temp_v0_10;
        if (temp_v0_10 > 0x80000) {
            e->velocityY_fixed = 0x80000;
        }
        var_s1 = temp_s1 + e->velocityY_fixed;
    } else {
        temp_v1_4 = e->velocityY_fixed;
        temp_s1_2 = temp_s1 + (e->pushY << 0x10);
        if (temp_v1_4 > 0) {
            var_s1 = temp_s1_2 + 0xC000;
        } else {
            var_s1 = temp_s1_2 + temp_v1_4;
        }
    }
    e->sprite.base.worldY = (s16) (var_s1 >> 0x10);
    e->sprite.base.velocityY = var_s1;
    if (e->velocityY_fixed < 0) {
        temp_v0_11 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) ((u16) e->sprite.base.worldY - 0x40));
        sp24 = temp_v0_11;
        if (((u32) ((temp_v0_11 + 0x4B) & 0xFF) < 3U) || (temp_a0_7 = temp_v0_11 & 0xFF, (temp_a0_7 == 0xC9)) || (temp_a0_7 == 0xCB) || (var_v0_7 = 0, (((u32) ((temp_v0_11 + 0x23) & 0xFF) < 3U) != 0))) {
            if (e->invincibilityTimer != 0) {
                sp24 = 0x65;
                var_v0_7 = 0;
            } else {
                var_v0_7 = 1;
            }
        }
        if (var_v0_7 & 0xFF) {
            temp_a0_8 = S16AT(e, 0x2E);
            temp_v1_5 = (u16) e->sprite.base.worldY - 0x40;
            if (temp_a0_8 != 0) {
                if (temp_a0_8 > 0) {
                    temp_v0_12 = (temp_a0_8 * 8) + S32AT(e, S16AT(e, 0x30));
                    var_s6 = S32AT(temp_v0_12, -8);
                    var_a2_2 = S32AT(temp_v0_12, -4);
                } else {
                    var_a2_2 = e->sprite.base.moveCallbackY;
                }
                temp_v1_6 = S16AT(e, 0x2C);
                if ((temp_a0_8 << 0x10) > 0) {
                    var_v0_8 = (s16) var_s6 + temp_v1_6;
                } else {
                    var_v0_8 = temp_v1_6;
                }
                var_v0_9 = var_a2_2(e + var_v0_8, temp_v1_5) | 0xF;
            } else {
                var_v0_9 = temp_v1_5 | 0xF;
            }
            var_a1_3 = sp24;
            var_v0_10 = (s16) ((s32) (var_v0_9 << 0x10) / (s32) e->sprite.base.scalePowerupY) + 0x40;
            goto block_130;
        }
        if (sp24 == 0x65) {
            e->velocityY_fixed = 0;
            e->landingTimer = 0;
            e->bounceLockTimer = 0;
            e->jumpHoldCounter = 0;
            e->altSpeed = 0;
            PlayEntityPositionSound(e, 0x50F08207U);
            temp_a0_9 = S16AT(e, 0x2E);
            temp_v1_7 = (u16) e->sprite.base.worldY - 0x40;
            if (temp_a0_9 != 0) {
                if (temp_a0_9 > 0) {
                    temp_v0_13 = (temp_a0_9 * 8) + S32AT(e, S16AT(e, 0x30));
                    sp48 = S32AT(temp_v0_13, -8);
                    sp4C = S32AT(temp_v0_13, -4);
                    var_a2_3 = sp4C;
                } else {
                    var_a2_3 = e->sprite.base.moveCallbackY;
                }
                temp_v1_8 = S16AT(e, 0x2C);
                if ((temp_a0_9 << 0x10) > 0) {
                    var_v0_11 = (s16) sp48 + temp_v1_8;
                } else {
                    var_v0_11 = temp_v1_8;
                }
                var_v0_12 = var_a2_3(e + var_v0_11, temp_v1_7) | 0xF;
            } else {
                var_v0_12 = temp_v1_7 | 0xF;
            }
            var_a1_4 = D_800A5D30;
            var_a2_4 = D_800A5D34;
            e->sprite.base.worldY = (s16) ((s32) (var_v0_12 << 0x10) / (s32) e->sprite.base.scalePowerupY) + 0x40;
            goto block_219;
        }
        goto block_220;
        goto block_221;
    }
    var_v0_13 = 0 & 0xFF;
    if (e->velocityY_fixed > 0) {
        var_s3 = 0xC;
        if (e->sprite.base.facing != 0) {
            var_s3 = -0xC;
        }
        temp_v0_14 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, e->sprite.base.worldY);
        sp25 = temp_v0_14;
        if (((u32) ((temp_v0_14 + 0x4B) & 0xFF) < 3U) || (temp_a0_10 = temp_v0_14 & 0xFF, (temp_a0_10 == 0xC9)) || (temp_a0_10 == 0xCB) || (var_a0 = 0, (((u32) ((temp_v0_14 + 0x23) & 0xFF) < 3U) != 0))) {
            if (e->invincibilityTimer != 0) {
                sp25 = 0x65;
                var_a0 = 0;
            } else {
                var_a0 = 1;
            }
        }
        temp_s1_3 = sp25;
        if ((temp_s1_3 == 0x5B) || (temp_a3 = e->sprite.base.worldY, (((s16) ((s32) (S16AT(g_pGameState, 0x4A) << 0x10) / (s32) e->sprite.base.scalePowerupY) < temp_a3) != 0))) {
            if ((u16) e->powerupTimer == 0) {
                var_a1_5 = D_800A5D98;
                var_a2_5 = D_800A5D9C;
            } else {
                var_a1_5 = D_800A5D78;
                var_a2_5 = D_800A5D7C;
            }
            goto block_302;
        }
        if (var_a0 & 0xFF) {
            var_a1_3 = sp25;
            var_v0_10 = TransformYCoordWithScaleSnapped(e, temp_a3) - 1;
block_130:
            e->sprite.base.worldY = var_v0_10;
            PlayerProcessBounceCollision(e, var_a1_3);
            var_v0_13 = 0 & 0xFF;
            goto block_221;
        }
        if (temp_s1_3 == 0x7D) {
            temp_v0_15 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) (temp_a3 - 0x40));
            sp25 = temp_v0_15;
            if ((temp_v0_15 & 0xFF) == temp_s1_3) {
                temp_a0_11 = S16AT(e, 0x26);
                var_a1_6 = (u16) e->sprite.base.worldX;
                if (temp_a0_11 != 0) {
                    if (temp_a0_11 > 0) {
                        temp_v0_16 = (temp_a0_11 * 8) + S32AT(e, S16AT(e, 0x28));
                        sp60 = S32AT(temp_v0_16, -8);
                        sp64 = S32AT(temp_v0_16, -4);
                        var_a2_6 = sp64;
                    } else {
                        var_a2_6 = e->sprite.base.moveCallbackX;
                    }
                    temp_v1_9 = S16AT(e, 0x24);
                    if ((temp_a0_11 << 0x10) > 0) {
                        var_v0_14 = (s16) sp60 + temp_v1_9;
                    } else {
                        var_v0_14 = temp_v1_9;
                    }
                    var_a1_6 = var_a2_6(e + var_v0_14, (s16) var_a1_6);
                }
                var_v0_15 = var_a1_6 & ~0xF;
                goto block_218;
            }
            goto block_220;
        }
        var_s2_2 = 0;
        if (temp_s1_3 == 0x65) {
            e->sprite.base.worldY = TransformYCoordWithScaleSnapped(e, temp_a3) - 1;
            var_s4 = 1;
        } else {
            var_v0_16 = 0;
            if (temp_s1_3 != 0) {
                var_v0_16 = temp_s1_3 < 0x3CU;
            }
            if ((var_v0_16 != 0) && (IsEntityNearSoundTrigger(e, temp_s1_3, e->sprite.base.worldX, temp_a3, (s32) temp_a3) & 0xFF)) {
                var_s2_2 = 1;
            }
            if (var_s2_2 != 0) {
                var_a1_7 = sp25;
                var_a3_2 = e->sprite.base.worldY;
                var_s4 = 1;
                goto block_158;
            }
            var_s2_3 = 0;
            temp_v0_17 = EntityApplyMovementCallbacks(e, e->sprite.base.worldX, (s16) ((u16) e->sprite.base.worldY - 8));
            temp_a1 = temp_v0_17 & 0xFF;
            var_v1 = 0;
            if (temp_a1 != 0) {
                var_v1 = temp_a1 < 0x3CU;
            }
            if (var_v1 != 0) {
                temp_v0_18 = (u16) e->sprite.base.worldY;
                if (IsEntityNearSoundTrigger(e, temp_a1, e->sprite.base.worldX, (s16) (temp_v0_18 - 8), (s32) (s16) temp_v0_18) & 0xFF) {
                    var_s2_3 = 1;
                }
            }
            if (var_s2_3 != 0) {
                var_a1_7 = temp_v0_17 & 0xFF;
                var_s4 = 1;
                var_a3_2 = (u16) e->sprite.base.worldY - 8;
block_158:
                e->sprite.base.worldY = PlayerApplyPositionWithCollision(e, var_a1_7, e->sprite.base.worldX, var_a3_2);
            }
        }
        if (!(var_s4 & 0xFF)) {
            temp_v0_19 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s3), (s16) (TransformYCoordWithScaleSnapped(e, e->sprite.base.worldY) - 1));
            sp25 = temp_v0_19;
            if ((((u32) ((temp_v0_19 + 0x4B) & 0xFF) < 3U) || (temp_a0_12 = temp_v0_19 & 0xFF, (temp_a0_12 == 0xC9)) || (temp_a0_12 == 0xCB) || ((u32) ((temp_v0_19 + 0x23) & 0xFF) < 3U)) && (e->invincibilityTimer != 0)) {
                sp25 = 0x65;
            }
            if (sp25 != 0x65) {
                temp_v0_20 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s3), e->sprite.base.worldY);
                sp25 = temp_v0_20;
                if (((u32) ((temp_v0_20 + 0x4B) & 0xFF) < 3U) || (temp_a0_13 = temp_v0_20 & 0xFF, (temp_a0_13 == 0xC9)) || (temp_a0_13 == 0xCB) || (var_a0_2 = 0, (((u32) ((temp_v0_20 + 0x23) & 0xFF) < 3U) != 0))) {
                    if (e->invincibilityTimer != 0) {
                        sp25 = 0x65;
                        var_a0_2 = 0;
                    } else {
                        var_a0_2 = 1;
                    }
                }
                if (var_a0_2 & 0xFF) {
                    e->sprite.base.worldY = TransformYCoordWithScaleSnapped(e, e->sprite.base.worldY) - 1;
                    PlayerProcessBounceCollision(e, sp25);
                    var_v0_17 = var_s4 & 0xFF;
                } else {
                    var_s1_2 = 0;
                    if (sp25 == 0x65) {
                        var_s4 = 1;
                        e->sprite.base.worldX = (u16) e->sprite.base.worldX + var_s3;
                        var_v0_18 = TransformYCoordWithScaleSnapped(e, e->sprite.base.worldY) - 1;
                        goto block_194;
                    }
                    var_v0_19 = 0;
                    if (sp25 != 0) {
                        var_v0_19 = sp25 < 0x3CU;
                    }
                    if (var_v0_19 != 0) {
                        temp_a3_2 = e->sprite.base.worldY;
                        if (IsEntityNearSoundTrigger(e, sp25, (s16) ((u16) e->sprite.base.worldX + var_s3), temp_a3_2, (s32) temp_a3_2) & 0xFF) {
                            var_s1_2 = 1;
                        }
                    }
                    if (var_s1_2 != 0) {
                        var_s4 = 1;
                        var_a1_8 = sp25;
                        var_a3_3 = e->sprite.base.worldY;
                        var_v0_20 = (u16) e->sprite.base.worldX + var_s3;
                        var_a2_7 = var_v0_20 + var_s3;
                        goto block_193;
                    }
                    var_s2_4 = 0;
                    temp_s1_4 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s3), (s16) ((u16) e->sprite.base.worldY - 8)) & 0xFF;
                    var_v1_2 = 0;
                    if (temp_s1_4 != 0) {
                        var_v1_2 = temp_s1_4 < 0x3CU;
                    }
                    if (var_v1_2 != 0) {
                        temp_v0_21 = (u16) e->sprite.base.worldY;
                        if (IsEntityNearSoundTrigger(e, temp_s1_4, (s16) ((u16) e->sprite.base.worldX + var_s3), (s16) (temp_v0_21 - 8), (s32) (s16) temp_v0_21) & 0xFF) {
                            var_s2_4 = 1;
                        }
                    }
                    if (var_s2_4 != 0) {
                        var_a1_8 = temp_s1_4;
                        var_s4 = 1;
                        var_v0_20 = (u16) e->sprite.base.worldX + var_s3;
                        var_a2_7 = var_v0_20 + var_s3;
                        var_a3_3 = (u16) e->sprite.base.worldY - 8;
block_193:
                        e->sprite.base.worldX = var_v0_20;
                        var_v0_18 = PlayerApplyPositionWithCollision(e, var_a1_8, var_a2_7, var_a3_3);
block_194:
                        e->sprite.base.worldY = var_v0_18;
                    }
                    goto block_195;
                }
            } else {
block_195:
                var_v0_17 = var_s4 & 0xFF;
            }
            if (var_v0_17 == 0) {
                var_v0_13 = var_s4 & 0xFF;
                if (0 == 0) {
                    temp_v0_22 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + 0x10), e->sprite.base.worldY);
                    sp25 = temp_v0_22;
                    if ((temp_v0_22 & 0xFF) == 0x7D) {
                        temp_v0_23 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + 0x10), (s16) ((u16) e->sprite.base.worldY - 0x40));
                        sp25 = temp_v0_23;
                        if ((temp_v0_23 & 0xFF) == 0x7D) {
                            temp_a0_14 = S16AT(e, 0x26);
                            var_v1_3 = (u16) e->sprite.base.worldX + 0x10;
                            var_a1_9 = var_v1_3;
                            if (temp_a0_14 != 0) {
                                if (temp_a0_14 > 0) {
                                    temp_v0_24 = (temp_a0_14 * 8) + S32AT(e, S16AT(e, 0x28));
                                    sp70 = S32AT(temp_v0_24, -8);
                                    sp74 = S32AT(temp_v0_24, -4);
                                    var_a2_8 = sp74;
                                } else {
                                    var_a2_8 = e->sprite.base.moveCallbackX;
                                }
                                if ((temp_a0_14 << 0x10) > 0) {
                                    var_v0_21 = sp70 << 0x10;
                                    goto block_214;
                                }
                                goto block_215;
                                goto block_216;
                            }
                            goto block_217;
                        }
                    } else {
                        temp_v0_25 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX - 0x10), e->sprite.base.worldY);
                        temp_s1_5 = temp_v0_25 & 0xFF;
                        sp25 = temp_v0_25;
                        if (temp_s1_5 == 0x7D) {
                            temp_v0_26 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX - 0x10), (s16) ((u16) e->sprite.base.worldY - 0x40));
                            sp25 = temp_v0_26;
                            if ((temp_v0_26 & 0xFF) == temp_s1_5) {
                                temp_a0_15 = S16AT(e, 0x26);
                                var_v1_3 = (u16) e->sprite.base.worldX - 0x10;
                                var_a1_9 = var_v1_3;
                                if (temp_a0_15 != 0) {
                                    if (temp_a0_15 > 0) {
                                        temp_v0_27 = (temp_a0_15 * 8) + S32AT(e, S16AT(e, 0x28));
                                        sp80 = S32AT(temp_v0_27, -8);
                                        sp84 = S32AT(temp_v0_27, -4);
                                        var_a2_8 = sp84;
                                    } else {
                                        var_a2_8 = e->sprite.base.moveCallbackX;
                                    }
                                    if ((temp_a0_15 << 0x10) > 0) {
                                        var_v0_21 = sp80 << 0x10;
block_214:
                                        var_v0_22 = (var_v0_21 >> 0x10) + S16AT(e, 0x24);
                                    } else {
block_215:
                                        var_v0_22 = S16AT(e, 0x24);
                                    }
block_216:
                                    var_v1_3 = var_a2_8(e + var_v0_22, var_a1_9);
                                }
block_217:
                                var_v0_15 = var_v1_3 & ~0xF;
block_218:
                                var_a1_4 = D_800A5ED4;
                                var_a2_4 = D_800A5ED8;
                                e->sprite.base.worldX = (s16) ((s32) (var_v0_15 << 0x10) / (s32) e->sprite.base.scalePowerupX) + 8;
block_219:
                                EntitySetState(e, var_a1_4, var_a2_4);
                            }
                        }
                    }
block_220:
                    var_v0_13 = var_s4 & 0xFF;
                }
                goto block_221;
            }
            goto block_286;
        }
        goto block_286;
    }
block_221:
    if (var_v0_13 == 0) {
        var_s3_2 = 0xC;
        if (e->sprite.base.facing != 0) {
            var_s3_2 = -0xC;
        }
        var_s1_3 = CheckEntityPointCollisionWithOffsets(e, 8, 0x100B, 0);
        if (var_s1_3 == NULL) {
            temp_a0_16 = S16AT(e, 0x26);
            temp_v1_10 = (u16) e->sprite.base.worldX + var_s3_2;
            if (temp_a0_16 != 0) {
                if (temp_a0_16 > 0) {
                    temp_v0_28 = (temp_a0_16 * 8) + S32AT(e, S16AT(e, 0x28));
                    sp90 = S32AT(temp_v0_28, -8);
                    sp94 = S32AT(temp_v0_28, -4);
                    var_a2_9 = sp94;
                } else {
                    var_a2_9 = e->sprite.base.moveCallbackX;
                }
                temp_v1_11 = S16AT(e, 0x24);
                if ((temp_a0_16 << 0x10) > 0) {
                    var_v0_23 = (s16) sp90 + temp_v1_11;
                } else {
                    var_v0_23 = temp_v1_11;
                }
                var_v0_24 = var_a2_9(e + var_v0_23, temp_v1_10) << 0x10;
            } else {
                var_v0_24 = temp_v1_10 << 0x10;
            }
            temp_a0_17 = S16AT(e, 0x2E);
            temp_a1_2 = (u16) e->sprite.base.worldY;
            if (temp_a0_17 != 0) {
                if (temp_a0_17 > 0) {
                    temp_v0_29 = (temp_a0_17 * 8) + S32AT(e, S16AT(e, 0x30));
                    spA0 = S32AT(temp_v0_29, -8);
                    spA4 = S32AT(temp_v0_29, -4);
                    var_a3_4 = spA4;
                } else {
                    var_a3_4 = e->sprite.base.moveCallbackY;
                }
                temp_v1_12 = S16AT(e, 0x2C);
                if ((temp_a0_17 << 0x10) > 0) {
                    var_v0_25 = (s16) spA0 + temp_v1_12;
                } else {
                    var_v0_25 = temp_v1_12;
                }
                var_v0_26 = var_a3_4(e + var_v0_25, (s16) temp_a1_2);
            } else {
                var_v0_26 = (s16) temp_a1_2;
            }
            var_s1_3 = CheckPointCollisionAndNotify(g_pGameState, var_v0_24 >> 0x10, var_v0_26, 8, 0x100B, 0, e);
            var_v0_27 = var_s4 & 0xFF;
            if (var_s1_3 != NULL) {
                goto block_244;
            }
        } else {
block_244:
            var_s2_5 = S32AT(var_s1_3, 0x114);
            if (e->sprite.base.scalePowerupX == 0x8000) {
                var_s2_5 *= 2;
            }
            GetEntityScreenBounds(var_s1_3, &sp28);
            temp_lo = (s32) (sp28 << 0x10) / (s32) e->sprite.base.scalePowerupX;
            sp28 = (s16) temp_lo;
            temp_lo_2 = (s32) (sp2C << 0x10) / (s32) e->sprite.base.scalePowerupX;
            sp2C = (s16) temp_lo_2;
            temp_lo_3 = (s32) (sp2A << 0x10) / (s32) e->sprite.base.scalePowerupY;
            sp2A = (s16) temp_lo_3;
            sp2E = (s16) ((s32) (sp2E << 0x10) / (s32) e->sprite.base.scalePowerupY);
            if (((e->velocityY_fixed - var_s2_5) > 0) && ((e->sprite.base.worldY - (s16) temp_lo_3) < (0xD - (var_s2_5 >> 0x10)))) {
                temp_v1_13 = e->sprite.base.worldX;
                var_v0_28 = var_s3_2 << 0x10;
                if (((temp_v1_13 >= (s16) temp_lo) && (var_v0_28 = var_s3_2 << 0x10, (((s16) temp_lo_2 < temp_v1_13) == 0))) || ((temp_v1_14 = temp_v1_13 + (var_v0_28 >> 0x10), var_v0_27 = var_s4 & 0xFF, ((temp_v1_14 < (s16) temp_lo) == 0)) && (var_v0_27 = var_s4 & 0xFF, (((s16) temp_lo_2 < temp_v1_14) == 0)))) {
                    temp_a0_18 = e->sprite.base.worldX;
                    if ((temp_a0_18 < sp28) || (sp2C < temp_a0_18)) {
                        e->sprite.base.worldX = temp_a0_18 + var_s3_2;
                    }
                    var_a2_10 = e->velocityY_fixed;
                    e->interactEntity = var_s1_3;
                    e->sprite.base.worldY = (u16) sp2A - 1;
                    if (e->sprite.base.scalePowerupX == 0x8000) {
                        var_a2_10 = var_a2_10 >> 1;
                    }
                    temp_a1_3 = S16AT(var_s1_3, 0xA);
                    if (temp_a1_3 != 0) {
                        if (temp_a1_3 > 0) {
                            temp_v0_30 = (temp_a1_3 * 8) + S32AT(var_s1_3, S16AT(var_s1_3, 0xC));
                            spB8 = S32AT(temp_v0_30, -8);
                            spBC = S32AT(temp_v0_30, -4);
                            var_t0 = spBC;
                        } else {
                            var_t0 = var_s1_3->eventCallback;
                        }
                        temp_v1_15 = S16AT(var_s1_3, 0x8);
                        if ((temp_a1_3 << 0x10) > 0) {
                            var_v0_29 = (s16) spB8 + temp_v1_15;
                        } else {
                            var_v0_29 = temp_v1_15;
                        }
                        var_t0(var_s1_3 + var_v0_29);
                    }
                    temp_a0_19 = e->interactEntity;
                    temp_a2 = S16AT(temp_a0_19, 0x26);
                    temp_a1_4 = (u16) temp_a0_19->worldX;
                    if (temp_a2 != 0) {
                        if (temp_a2 > 0) {
                            temp_v0_31 = (temp_a2 * 8) + S32AT(temp_a0_19, S16AT(temp_a0_19, 0x28));
                            spC8 = S32AT(temp_v0_31, -8);
                            spCC = S32AT(temp_v0_31, -4);
                            var_a2_11 = spCC;
                        } else {
                            var_a2_11 = temp_a0_19->moveCallbackX;
                        }
                        temp_v1_16 = S16AT(temp_a0_19, 0x24);
                        if ((temp_a2 << 0x10) > 0) {
                            var_v0_30 = (s16) spC8 + temp_v1_16;
                        } else {
                            var_v0_30 = temp_v1_16;
                        }
                        var_v1_4 = var_a2_11(temp_a0_19 + var_v0_30, (s16) temp_a1_4);
                    } else {
                        var_v1_4 = (s16) temp_a1_4;
                    }
                    temp_a0_20 = e->interactEntity;
                    e->platformOffsetX = (u16) e->sprite.base.worldX - ((s32) (var_v1_4 << 0x10) / (s32) e->sprite.base.scalePowerupX);
                    temp_a2_2 = S16AT(temp_a0_20, 0x2E);
                    temp_a1_5 = (u16) temp_a0_20->worldY;
                    if (temp_a2_2 != 0) {
                        if (temp_a2_2 > 0) {
                            temp_v0_32 = (temp_a2_2 * 8) + S32AT(temp_a0_20, S16AT(temp_a0_20, 0x30));
                            spD8 = S32AT(temp_v0_32, -8);
                            spDC = S32AT(temp_v0_32, -4);
                            var_a2_12 = spDC;
                        } else {
                            var_a2_12 = temp_a0_20->moveCallbackY;
                        }
                        temp_v1_17 = S16AT(temp_a0_20, 0x2C);
                        if ((temp_a2_2 << 0x10) > 0) {
                            var_v0_31 = (s16) spD8 + temp_v1_17;
                        } else {
                            var_v0_31 = temp_v1_17;
                        }
                        var_v1_5 = var_a2_12(temp_a0_20 + var_v0_31, (s16) temp_a1_5);
                    } else {
                        var_v1_5 = (s16) temp_a1_5;
                    }
                    var_s4 = 1;
                    e->platformOffsetY = (u16) e->sprite.base.worldY - ((s32) (var_v1_5 << 0x10) / (s32) e->sprite.base.scalePowerupY);
                    goto block_284;
                }
            } else {
block_284:
                var_v0_27 = var_s4 & 0xFF;
            }
        }
        if (var_v0_27 != 0) {
            goto block_286;
        }
        if (e->velocityY_fixed > 0) {
            var_s1_4 = 0x10;
            if (e->sprite.base.facing != 0) {
                var_s1_4 = -0x10;
            }
            temp_s2 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s1_4), e->sprite.base.worldY);
            temp_s0 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s1_4), (s16) ((u16) e->sprite.base.worldY + 0x10));
            var_a0_3 = 0;
            var_v1_6 = 0;
            temp_s0_2 = temp_s0 & 0xFF;
            temp_a1_6 = EntityApplyMovementCallbacks(e, (s16) ((u16) e->sprite.base.worldX + var_s1_4), (s16) ((u16) e->sprite.base.worldY - 0xF));
            if (temp_s0_2 != 0) {
                var_v1_6 = temp_s0_2 < 0x3CU;
            }
            if ((var_v1_6 != 0) || (var_v1_7 = temp_s2 & 0xFF, (temp_s0_2 == 0x65))) {
                temp_v1_18 = temp_s2 & 0xFF;
                var_v0_32 = 0;
                if (temp_v1_18 != 0) {
                    var_v0_32 = temp_v1_18 < 0x3CU;
                }
                if ((var_v0_32 != 0) || (temp_v1_18 == 0x65)) {
                    var_v1_7 = temp_s2 & 0xFF;
                    goto block_315;
                }
                goto block_323;
            }
block_315:
            var_v0_33 = 0;
            if (var_v1_7 != 0) {
                var_v0_33 = var_v1_7 < 0x3CU;
            }
            if ((var_v0_33 != 0) || (var_v1_7 == 0x65)) {
                temp_v1_19 = temp_a1_6 & 0xFF;
                var_v0_34 = 0;
                if (temp_v1_19 != 0) {
                    var_v0_34 = temp_v1_19 < 0x3CU;
                }
                if ((var_v0_34 == 0) && (temp_v1_19 != 0x65)) {
block_323:
                    var_a0_3 = 1;
                }
            }
            if (var_a0_3 != 0) {
                U8AT(g_pGameState, 0x60) = 0;   /* bounce_active_flag */
            }
        }
        return;
    }
block_286:
    if ((e->timer13C != 0) && (D_800A596C_j & e->pInput->buttons_held)) {
        SpawnPlayerDeathEffect(e, 1);
        if (e->specialMoveMode != 0) {
            var_a1_5 = D_800A5E00;
            var_a2_5 = D_800A5E04;
        } else {
            var_a1_5 = D_800A5EDC;
            var_a2_5 = D_800A5EE0;
        }
    } else {
        temp_v1_20 = e->pInput->buttons_held;
        if (temp_v1_20 & 0x2000) {
            SpawnPlayerDeathEffect(e, 1);
            e->sprite.base.facing = 0;
            if (e->specialMoveMode != 0) {
                var_a1_5 = D_800A5E08;
                var_a2_5 = D_800A5E0C;
            } else {
                var_a1_5 = D_800A5E58;
                var_a2_5 = D_800A5E5C;
            }
        } else if (temp_v1_20 & 0x8000) {
            SpawnPlayerDeathEffect(e, 1);
            e->sprite.base.facing = 1;
            if (e->specialMoveMode != 0) {
                var_a1_5 = D_800A5E08;
                var_a2_5 = D_800A5E0C;
            } else {
                var_a1_5 = D_800A5E58;
                var_a2_5 = D_800A5E5C;
            }
        } else if (e->specialMoveMode != 0) {
            SpawnPlayerDeathEffect(e, 1);
            var_a1_5 = D_800A5EE4;
            var_a2_5 = D_800A5EE8;
        } else {
            SpawnPlayerDeathEffect(e, 0);
            var_a1_5 = D_800A5EEC;
            var_a2_5 = D_800A5EF0;
        }
    }
block_302:
    EntitySetState(e, var_a1_5, var_a2_5);
}
