# Ghidra Python script to create callback functions
# Auto-generated by generate_ghidra_script.py
# Run this in Ghidra's Script Manager (Window > Script Manager)

from ghidra.program.model.symbol import SourceType
from ghidra.app.cmd.function import CreateFunctionCmd

# List of (address, name) tuples
FUNCTIONS_TO_CREATE = [
    (0x80012798, "Callback_80012798"),
    (0x800127A4, "Callback_800127a4"),
    (0x800127B0, "Callback_800127b0"),
    (0x800127BC, "Callback_800127bc"),
    (0x800127C8, "Callback_800127c8"),
    (0x800127D4, "Callback_800127d4"),
    (0x800127E0, "Callback_800127e0"),
    (0x800127EC, "Callback_800127ec"),
    (0x800127F0, "Callback_800127f0"),
    (0x800127FC, "Callback_800127fc"),
    (0x8001280C, "Callback_8001280c"),
    (0x80012818, "Callback_80012818"),
    (0x80012820, "Callback_80012820"),
    (0x8001282C, "Callback_8001282c"),
    (0x80012838, "Callback_80012838"),
    (0x80012840, "Callback_80012840"),
    (0x8001284C, "Callback_8001284c"),
    (0x80012858, "Callback_80012858"),
    (0x80012864, "Callback_80012864"),
    (0x80012870, "Callback_80012870"),
    (0x80012878, "Callback_80012878"),
    (0x80012884, "Callback_80012884"),
    (0x8001288C, "Callback_8001288c"),
    (0x80012894, "Callback_80012894"),
    (0x800128A0, "Callback_800128a0"),
    (0x800128A8, "Callback_800128a8"),
    (0x800128B4, "Callback_800128b4"),
    (0x800128C0, "Callback_800128c0"),
    (0x800128CC, "Callback_800128cc"),
    (0x80012990, "Callback_80012990"),
    (0x80012C44, "Callback_80012c44"),
    (0x80012CDC, "Callback_80012cdc"),
    (0x80012E48, "Callback_80012e48"),
    (0x800270A8, "Callback_800270a8"),
    (0x8002713C, "Callback_8002713c"),
    (0x800271CC, "Callback_800271cc"),
    (0x8002E5A0, "Callback_8002e5a0"),
    (0x8002E60C, "Callback_8002e60c"),
    (0x8002E65C, "Callback_8002e65c"),
    (0x8002E70C, "Callback_8002e70c"),
    (0x8002FA94, "Callback_8002fa94"),
    (0x8002FB04, "Callback_8002fb04"),
    (0x8002FE20, "Callback_8002fe20"),
    (0x8003C540, "Callback_8003c540"),
    (0x8003C568, "Callback_8003c568"),
    (0x8003C590, "Callback_8003c590"),
    (0x8003CD8C, "Callback_8003cd8c"),
    (0x8003CF20, "Callback_8003cf20"),
    (0x8003D3FC, "Callback_8003d3fc"),
    (0x8003D564, "Callback_8003d564"),
    (0x8003DD20, "Callback_8003dd20"),
    (0x8003DEFC, "Callback_8003defc"),
    (0x8003E8D8, "Callback_8003e8d8"),
    (0x8003E900, "Callback_8003e900"),
    (0x8003E928, "Callback_8003e928"),
    (0x8003EEA0, "Callback_8003eea0"),
    (0x8003F9AC, "Callback_8003f9ac"),
    (0x8003FB40, "Callback_8003fb40"),
    (0x80040624, "Callback_80040624"),
    (0x8004207C, "Callback_8004207c"),
    (0x800420F4, "Callback_800420f4"),
    (0x80042AAC, "Callback_80042aac"),
    (0x80042B24, "Callback_80042b24"),
    (0x80043070, "Callback_80043070"),
    (0x800430E4, "Callback_800430e4"),
    (0x8004319C, "Callback_8004319c"),
    (0x800435B0, "Callback_800435b0"),
    (0x80044C48, "Callback_80044c48"),
    (0x800455BC, "Callback_800455bc"),
    (0x800467B8, "Callback_800467b8"),
    (0x800467E0, "Callback_800467e0"),
    (0x80046B38, "Callback_80046b38"),
    (0x80046B88, "Callback_80046b88"),
    (0x800479D0, "Callback_800479d0"),
    (0x80047EE4, "Callback_80047ee4"),
    (0x80048D60, "Callback_80048d60"),
    (0x80048F40, "Callback_80048f40"),
    (0x8004906C, "Callback_8004906c"),
    (0x8004A768, "Callback_8004a768"),
    (0x8004A814, "Callback_8004a814"),
    (0x8004A84C, "Callback_8004a84c"),
    (0x8004A930, "Callback_8004a930"),
    (0x8004AA08, "Callback_8004aa08"),
    (0x8004AA40, "Callback_8004aa40"),
    (0x8004AB60, "Callback_8004ab60"),
    (0x8004AC4C, "Callback_8004ac4c"),
    (0x8004ACD4, "Callback_8004acd4"),
    (0x8004AD5C, "Callback_8004ad5c"),
    (0x8004ADE4, "Callback_8004ade4"),
    (0x8004BA74, "Callback_8004ba74"),
    (0x8004BAC8, "Callback_8004bac8"),
    (0x8004BC90, "Callback_8004bc90"),
    (0x8004BD44, "Callback_8004bd44"),
    (0x8004BDFC, "Callback_8004bdfc"),
    (0x8004BEE0, "Callback_8004bee0"),
    (0x8004BFC4, "Callback_8004bfc4"),
    (0x8004CE74, "Callback_8004ce74"),
    (0x8004D264, "Callback_8004d264"),
    (0x8004D32C, "Callback_8004d32c"),
    (0x8004D61C, "Callback_8004d61c"),
    (0x8004D628, "Callback_8004d628"),
    (0x8004D6DC, "Callback_8004d6dc"),
    (0x8004D790, "Callback_8004d790"),
    (0x8004E9F4, "Callback_8004e9f4"),
    (0x8004EAC8, "Callback_8004eac8"),
    (0x8004EB94, "Callback_8004eb94"),
    (0x800505A0, "Callback_800505a0"),
    (0x800505FC, "Callback_800505fc"),
    (0x80051184, "Callback_80051184"),
    (0x80051D44, "Callback_80051d44"),
    (0x80051DF4, "Callback_80051df4"),
    (0x80051EA4, "Callback_80051ea4"),
    (0x800521C8, "Callback_800521c8"),
    (0x80053D70, "Callback_80053d70"),
    (0x80053EDC, "Callback_80053edc"),
    (0x80053F14, "Callback_80053f14"),
    (0x80053FB8, "Callback_80053fb8"),
    (0x80054550, "Callback_80054550"),
    (0x80054600, "Callback_80054600"),
    (0x80057020, "Callback_80057020"),
    (0x800570A4, "Callback_800570a4"),
    (0x800574A4, "Callback_800574a4"),
    (0x80057500, "Callback_80057500"),
    (0x80066F60, "Callback_80066f60"),
    (0x800670BC, "Callback_800670bc"),
    (0x800672F4, "Callback_800672f4"),
    (0x8006736C, "Callback_8006736c"),
    (0x800674CC, "Callback_800674cc"),
    (0x8006762C, "Callback_8006762c"),
    (0x80067798, "Callback_80067798"),
    (0x800678D4, "Callback_800678d4"),
    (0x80067A34, "Callback_80067a34"),
    (0x80067CF0, "Callback_80067cf0"),
    (0x80067E28, "Callback_80067e28"),
    (0x80067F90, "Callback_80067f90"),
    (0x80067FC8, "Callback_80067fc8"),
    (0x80068130, "Callback_80068130"),
    (0x800682A4, "Callback_800682a4"),
    (0x8006888C, "Callback_8006888c"),
    (0x80068A0C, "Callback_80068a0c"),
    (0x80068B48, "Callback_80068b48"),
    (0x80068D38, "Callback_80068d38"),
    (0x80068F80, "Callback_80068f80"),
    (0x800691D8, "Callback_800691d8"),
    (0x800691E8, "Callback_800691e8"),
    (0x80069200, "Callback_80069200"),
    (0x80069754, "Callback_80069754"),
    (0x800698B8, "Callback_800698b8"),
    (0x80069A3C, "Callback_80069a3c"),
    (0x80069BBC, "Callback_80069bbc"),
    (0x80069D3C, "Callback_80069d3c"),
    (0x80069EA4, "Callback_80069ea4"),
    (0x80069EF4, "Callback_80069ef4"),
    (0x8006A0B8, "Callback_8006a0b8"),
    (0x8006A214, "Callback_8006a214"),
    (0x8006A3F8, "Callback_8006a3f8"),
    (0x8006A584, "Callback_8006a584"),
    (0x8006A6E4, "Callback_8006a6e4"),
    (0x8006A940, "Callback_8006a940"),
    (0x8006AA9C, "Callback_8006aa9c"),
    (0x8006ABF8, "Callback_8006abf8"),
    (0x8006AD34, "Callback_8006ad34"),
    (0x8006AD70, "Callback_8006ad70"),
    (0x8006ADBC, "Callback_8006adbc"),
    (0x8006AE58, "Callback_8006ae58"),
    (0x8006AE94, "Callback_8006ae94"),
    (0x8006AEDC, "Callback_8006aedc"),
    (0x8006AF28, "Callback_8006af28"),
    (0x8006B2DC, "Callback_8006b2dc"),
    (0x8006B3F8, "Callback_8006b3f8"),
    (0x8006B4F4, "Callback_8006b4f4"),
    (0x8006B634, "Callback_8006b634"),
    (0x8006B658, "Callback_8006b658"),
    (0x8006B7F8, "Callback_8006b7f8"),
    (0x8006B974, "Callback_8006b974"),
    (0x8006BC04, "Callback_8006bc04"),
    (0x8006BD80, "Callback_8006bd80"),
    (0x8006BDD4, "Callback_8006bdd4"),
    (0x8006BF2C, "Callback_8006bf2c"),
    (0x8006C0AC, "Callback_8006c0ac"),
    (0x8006C0D8, "Callback_8006c0d8"),
    (0x8006C278, "Callback_8006c278"),
    (0x8006C3AC, "Callback_8006c3ac"),
    (0x8006C7CC, "Callback_8006c7cc"),
    (0x8006C95C, "Callback_8006c95c"),
    (0x8006D048, "Callback_8006d048"),
    (0x8006D3C8, "Callback_8006d3c8"),
    (0x8006D548, "Callback_8006d548"),
    (0x8006D6C8, "Callback_8006d6c8"),
    (0x8006D724, "Callback_8006d724"),
    (0x8006D910, "Callback_8006d910"),
    (0x8006E8F4, "Callback_8006e8f4"),
    (0x8006E960, "Callback_8006e960"),
    (0x8006EA0C, "Callback_8006ea0c"),
    (0x8006FDF4, "Callback_8006fdf4"),
    (0x8006FE94, "Callback_8006fe94"),
    (0x80070094, "Callback_80070094"),
    (0x800727B4, "Callback_800727b4"),
    (0x800727EC, "Callback_800727ec"),
    (0x800728E8, "Callback_800728e8"),
    (0x800729D8, "Callback_800729d8"),
    (0x80072A98, "Callback_80072a98"),
    (0x80072CAC, "Callback_80072cac"),
    (0x80072CE8, "Callback_80072ce8"),
    (0x80072DE0, "Callback_80072de0"),
    (0x80072FC4, "Callback_80072fc4"),
    (0x8007301C, "Callback_8007301c"),
    (0x800907EC, "Callback_800907ec"),
    (0x8009AE58, "Callback_8009ae58"),
    (0x8009B14C, "Callback_8009b14c"),
    (0x8009B160, "Callback_8009b160"),
    (0x8009B1D8, "Callback_8009b1d8"),
    (0x8009C270, "Callback_8009c270"),
    (0x8009C2A8, "Callback_8009c2a8"),
    (0x8009DF28, "Callback_8009df28"),
    (0x8009DF34, "Callback_8009df34"),
    (0x8009E1F8, "Callback_8009e1f8"),
    (0x8009E3B8, "Callback_8009e3b8"),
    (0x8009F420, "Callback_8009f420"),

]

def create_function_at(addr_int, name):
    """Create a function at the given address and rename it."""
    addr = toAddr(addr_int)
    
    # Check if function already exists
    func = getFunctionAt(addr)
    if func is not None:
        print("Function already exists at 0x{:08X}: {}".format(addr_int, func.getName()))
        # Rename if needed
        if func.getName().startswith("FUN_") or func.getName().startswith("LAB_"):
            func.setName(name, SourceType.USER_DEFINED)
            print("  -> Renamed to: {}".format(name))
        return True
    
    # Try to create the function
    cmd = CreateFunctionCmd(addr)
    if cmd.applyTo(currentProgram):
        func = getFunctionAt(addr)
        if func:
            func.setName(name, SourceType.USER_DEFINED)
            print("Created function at 0x{:08X}: {}".format(addr_int, name))
            return True
    
    # If that failed, try disassembling first
    print("Trying to disassemble at 0x{:08X}...".format(addr_int))
    disassemble(addr)
    
    # Try creating again
    cmd = CreateFunctionCmd(addr)
    if cmd.applyTo(currentProgram):
        func = getFunctionAt(addr)
        if func:
            func.setName(name, SourceType.USER_DEFINED)
            print("Created function at 0x{:08X}: {}".format(addr_int, name))
            return True
    
    print("FAILED to create function at 0x{:08X}".format(addr_int))
    return False


def main():
    print("Creating {} callback functions...".format(len(FUNCTIONS_TO_CREATE)))
    print("=" * 50)
    
    created = 0
    failed = 0
    
    for addr, name in FUNCTIONS_TO_CREATE:
        if create_function_at(addr, name):
            created += 1
        else:
            failed += 1
    
    print("=" * 50)
    print("Created: {}".format(created))
    print("Failed:  {}".format(failed))


if __name__ == "__main__":
    main()
else:
    main()

