#!/usr/bin/env python3
"""
Generate a Ghidra Python script to create unrecognized functions.

Since the MCP API's createFunction can fail when Ghidra hasn't analyzed
the code region, this script generates a Ghidra Python script that can
be run directly in Ghidra's Script Manager.

Usage:
    python3 scripts/generate_ghidra_script.py > scripts/create_functions.ghidra.py
    # Then run scripts/create_functions.ghidra.py in Ghidra's Script Manager
"""

import json
import sys

JSON_FILE = "build/unrecognized_functions.json"

SCRIPT_HEADER = '''# Ghidra Python script to create callback functions
# Auto-generated by generate_ghidra_script.py
# Run this in Ghidra's Script Manager (Window > Script Manager)

from ghidra.program.model.symbol import SourceType
from ghidra.app.cmd.function import CreateFunctionCmd

# List of (address, name) tuples
FUNCTIONS_TO_CREATE = [
'''

SCRIPT_FOOTER = '''
]

def create_function_at(addr_int, name):
    """Create a function at the given address and rename it."""
    addr = toAddr(addr_int)
    
    # Check if function already exists
    func = getFunctionAt(addr)
    if func is not None:
        print("Function already exists at 0x{:08X}: {}".format(addr_int, func.getName()))
        # Rename if needed
        if func.getName().startswith("FUN_") or func.getName().startswith("LAB_"):
            func.setName(name, SourceType.USER_DEFINED)
            print("  -> Renamed to: {}".format(name))
        return True
    
    # Try to create the function
    cmd = CreateFunctionCmd(addr)
    if cmd.applyTo(currentProgram):
        func = getFunctionAt(addr)
        if func:
            func.setName(name, SourceType.USER_DEFINED)
            print("Created function at 0x{:08X}: {}".format(addr_int, name))
            return True
    
    # If that failed, try disassembling first
    print("Trying to disassemble at 0x{:08X}...".format(addr_int))
    disassemble(addr)
    
    # Try creating again
    cmd = CreateFunctionCmd(addr)
    if cmd.applyTo(currentProgram):
        func = getFunctionAt(addr)
        if func:
            func.setName(name, SourceType.USER_DEFINED)
            print("Created function at 0x{:08X}: {}".format(addr_int, name))
            return True
    
    print("FAILED to create function at 0x{:08X}".format(addr_int))
    return False


def main():
    print("Creating {} callback functions...".format(len(FUNCTIONS_TO_CREATE)))
    print("=" * 50)
    
    created = 0
    failed = 0
    
    for addr, name in FUNCTIONS_TO_CREATE:
        if create_function_at(addr, name):
            created += 1
        else:
            failed += 1
    
    print("=" * 50)
    print("Created: {}".format(created))
    print("Failed:  {}".format(failed))


if __name__ == "__main__":
    main()
else:
    main()
'''


def get_suggested_name(item: dict) -> str:
    """Generate a suggested name for the function."""
    table = item.get("table", "")
    index = item.get("index", -1)
    offset = item.get("offset", 0)
    addr = item.get("address", 0)
    
    if table == "EntityTypeCallbacks" and index >= 0:
        cb_type = "Init" if offset == 0 else "Tick"
        return f"EntityType{index:03d}_{cb_type}Callback"
    elif table == "PlayerStateCallbacks" and index >= 0:
        return f"PlayerStateCallback_{index}"
    else:
        return f"Callback_{addr:08x}"


def main():
    try:
        with open(JSON_FILE, "r") as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: {JSON_FILE} not found. Run find_unrecognized_functions.py first.", 
              file=sys.stderr)
        sys.exit(1)
    
    results = data.get("results", [])
    
    print(SCRIPT_HEADER, end="")
    
    for item in results:
        addr = item.get("address", 0)
        name = get_suggested_name(item)
        print(f"    (0x{addr:08X}, \"{name}\"),")
    
    print(SCRIPT_FOOTER)


if __name__ == "__main__":
    main()
